### ISSUE TITLE
Can't PIP instsall OpentimelineIO

### ISSUE THREAD

**Issue by cyborgbabe** [PixarAnimationStudios/OpenTimelineIO#1048]
Hi everyone! 
I'm going a tiny bit crazy trying to install OpentimelineIO so that I can export videos on Kdenlive, but so far it's been impossible. I'm operating on Ubuntu 21.04; KDA plasma 5.21.4. 

I've installed PIP and upgraded the wheel requirements, and intalled Cmake, but when trying to install OpentimelineIO I keep getting an error sayig said file doesn't exist. 

>>  FileNotFoundError: [Errno 2] No such file or directory: 'cmake'

When repeating the command to install Cmake, I get this message: 

>> Requirement already satisfied: Cmake in ./.local/lib/python3.9/site-packages (3.21.1.post1)

I also keep getting the following errors:

>> Building wheel for opentimelineio (setup.py) ... error
>> ERROR: Command errored out with exit status 1:

alongside with several warnings for: 

>> no previously-included files found matching

several different things... 

I'm pretty new to python and linux, and open software.... Could anyone help me understand this error message? 
Thank you so much

$ python3 -m pip install opentimelineio
Defaulting to user installation because normal site-packages is not writeable
Collecting opentimelineio
  Using cached OpenTimelineIO-0.13.0.tar.gz (2.0 MB)
Requirement already satisfied: pyaaf2==1.4.0 in ./.local/lib/python3.9/site-packages (from opentimelineio) (1.4.0)
Building wheels for collected packages: opentimelineio

  **Building wheel for opentimelineio (setup.py) ... error**
  **ERROR: Command errored out with exit status 1:**
   command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8o713fqk/opentimelineio_6c9debc12bb7443190382115f6a8c322/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8o713fqk/opentimelineio_6c9debc12bb7443190382115f6a8c322/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-avoumh1p                               
       cwd: /tmp/pip-install-8o713fqk/opentimelineio_6c9debc12bb7443190382115f6a8c322/                                                                    

  Complete output (176 lines):                                               
  /home/ishtar/.local/lib/python3.9/site-packages/setuptools/dist.py:697: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead  
    warnings.warn(                                                           
  running bdist_wheel                                                        
  running build                                                              
  running build_py                                                           
  creating build                                                             
  creating build/lib.linux-x86_64-3.9                                        
  creating build/lib.linux-x86_64-3.9/opentimelineio                         
  copying src/py-opentimelineio/opentimelineio/media_linker.py -> build/lib.linux-x86_64-3.9/opentimelineio                                               
  copying src/py-opentimelineio/opentimelineio/opentime.py -> build/lib.linux-x86_64-3.9/opentimelineio                                                   
  copying src/py-opentimelineio/opentimelineio/test_utils.py -> build/lib.linux-x86_64-3.9/opentimelineio                                                 
  copying src/py-opentimelineio/opentimelineio/hooks.py -> build/lib.linux-x86_64-3.9/opentimelineio                                                      
  copying src/py-opentimelineio/opentimelineio/__init__.py -> build/lib.linux-x86_64-3.9/opentimelineio                                                   
  copying src/py-opentimelineio/opentimelineio/exceptions.py -> build/lib.linux-x86_64-3.9/opentimelineio                                                 
  creating build/lib.linux-x86_64-3.9/opentimelineio/core                    
  copying src/py-opentimelineio/opentimelineio/core/composition.py -> build/lib.linux-x86_64-3.9/opentimelineio/core                                      
  copying src/py-opentimelineio/opentimelineio/core/item.py -> build/lib.linux-x86_64-3.9/opentimelineio/core                                             
  copying src/py-opentimelineio/opentimelineio/core/composable.py -> build/lib.linux-x86_64-3.9/opentimelineio/core                                       
  copying src/py-opentimelineio/opentimelineio/core/__init__.py -> build/lib.linux-x86_64-3.9/opentimelineio/core                                         
  copying src/py-opentimelineio/opentimelineio/core/mediaReference.py -> build/lib.linux-x86_64-3.9/opentimelineio/core                                   
  copying src/py-opentimelineio/opentimelineio/core/_core_utils.py -> build/lib.linux-x86_64-3.9/opentimelineio/core                                      
  creating build/lib.linux-x86_64-3.9/opentimelineio/schemadef               
  copying src/py-opentimelineio/opentimelineio/schemadef/__init__.py -> build/lib.linux-x86_64-3.9/opentimelineio/schemadef                               
  creating build/lib.linux-x86_64-3.9/opentimelineio/console                 
  copying src/py-opentimelineio/opentimelineio/console/otiostat.py -> build/lib.linux-x86_64-3.9/opentimelineio/console                                   
  copying src/py-opentimelineio/opentimelineio/console/otiopluginfo.py -> build/lib.linux-x86_64-3.9/opentimelineio/console                               
  copying src/py-opentimelineio/opentimelineio/console/otiocat.py -> build/lib.linux-x86_64-3.9/opentimelineio/console                                    
  copying src/py-opentimelineio/opentimelineio/console/__init__.py -> build/lib.linux-x86_64-3.9/opentimelineio/console                                   
  copying src/py-opentimelineio/opentimelineio/console/autogen_plugin_documentation.py -> build/lib.linux-x86_64-3.9/opentimelineio/console               
  copying src/py-opentimelineio/opentimelineio/console/otioconvert.py -> build/lib.linux-x86_64-3.9/opentimelineio/console                                
  copying src/py-opentimelineio/opentimelineio/console/console_utils.py -> build/lib.linux-x86_64-3.9/opentimelineio/console                              
  copying src/py-opentimelineio/opentimelineio/console/autogen_serialized_datamodel.py -> build/lib.linux-x86_64-3.9/opentimelineio/console               
  creating build/lib.linux-x86_64-3.9/opentimelineio/adapters                
  copying src/py-opentimelineio/opentimelineio/adapters/adapter.py -> build/lib.linux-x86_64-3.9/opentimelineio/adapters                                  
  copying src/py-opentimelineio/opentimelineio/adapters/cmx_3600.py -> build/lib.linux-x86_64-3.9/opentimelineio/adapters                                 
  copying src/py-opentimelineio/opentimelineio/adapters/otio_json.py -> build/lib.linux-x86_64-3.9/opentimelineio/adapters                                
  copying src/py-opentimelineio/opentimelineio/adapters/fcp_xml.py -> build/lib.linux-x86_64-3.9/opentimelineio/adapters                                  
  copying src/py-opentimelineio/opentimelineio/adapters/__init__.py -> build/lib.linux-x86_64-3.9/opentimelineio/adapters                                 
  creating build/lib.linux-x86_64-3.9/opentimelineio/plugins                 
  copying src/py-opentimelineio/opentimelineio/plugins/python_plugin.py -> build/lib.linux-x86_64-3.9/opentimelineio/plugins                              
  copying src/py-opentimelineio/opentimelineio/plugins/manifest.py -> build/lib.linux-x86_64-3.9/opentimelineio/plugins                                   
  copying src/py-opentimelineio/opentimelineio/plugins/__init__.py -> build/lib.linux-x86_64-3.9/opentimelineio/plugins                                   
  creating build/lib.linux-x86_64-3.9/opentimelineio/algorithms              
  copying src/py-opentimelineio/opentimelineio/algorithms/timeline_algo.py -> build/lib.linux-x86_64-3.9/opentimelineio/algorithms                        
  copying src/py-opentimelineio/opentimelineio/algorithms/track_algo.py -> build/lib.linux-x86_64-3.9/opentimelineio/algorithms                           
  copying src/py-opentimelineio/opentimelineio/algorithms/__init__.py -> build/lib.linux-x86_64-3.9/opentimelineio/algorithms                             
  copying src/py-opentimelineio/opentimelineio/algorithms/stack_algo.py -> build/lib.linux-x86_64-3.9/opentimelineio/algorithms                           
  copying src/py-opentimelineio/opentimelineio/algorithms/filter.py -> build/lib.linux-x86_64-3.9/opentimelineio/algorithms                               
  creating build/lib.linux-x86_64-3.9/opentimelineio/schema                  
  copying src/py-opentimelineio/opentimelineio/schema/effect.py -> build/lib.linux-x86_64-3.9/opentimelineio/schema                                       
  copying src/py-opentimelineio/opentimelineio/schema/serializable_collection.py -> build/lib.linux-x86_64-3.9/opentimelineio/schema                      
  copying src/py-opentimelineio/opentimelineio/schema/marker.py -> build/lib.linux-x86_64-3.9/opentimelineio/schema                                       
  copying src/py-opentimelineio/opentimelineio/schema/schemadef.py -> build/lib.linux-x86_64-3.9/opentimelineio/schema                                    
  copying src/py-opentimelineio/opentimelineio/schema/foo.py -> build/lib.linux-x86_64-3.9/opentimelineio/schema                                          
  copying src/py-opentimelineio/opentimelineio/schema/external_reference.py -> build/lib.linux-x86_64-3.9/opentimelineio/schema                           
  copying src/py-opentimelineio/opentimelineio/schema/generator_reference.py -> build/lib.linux-x86_64-3.9/opentimelineio/schema                          
  copying src/py-opentimelineio/opentimelineio/schema/track.py -> build/lib.linux-x86_64-3.9/opentimelineio/schema                                        
  copying src/py-opentimelineio/opentimelineio/schema/image_sequence_reference.py -> build/lib.linux-x86_64-3.9/opentimelineio/schema                     
  copying src/py-opentimelineio/opentimelineio/schema/timeline.py -> build/lib.linux-x86_64-3.9/opentimelineio/schema                                     
  copying src/py-opentimelineio/opentimelineio/schema/clip.py -> build/lib.linux-x86_64-3.9/opentimelineio/schema                                         
  copying src/py-opentimelineio/opentimelineio/schema/__init__.py -> build/lib.linux-x86_64-3.9/opentimelineio/schema                                     
  copying src/py-opentimelineio/opentimelineio/schema/transition.py -> build/lib.linux-x86_64-3.9/opentimelineio/schema                                   
  copying src/py-opentimelineio/opentimelineio/schema/stack.py -> build/lib.linux-x86_64-3.9/opentimelineio/schema                                        
  creating build/lib.linux-x86_64-3.9/opentimelineview                       
  copying src/opentimelineview/timeline_widget.py -> build/lib.linux-x86_64-3.9/opentimelineview                                                          
  copying src/opentimelineview/details_widget.py -> build/lib.linux-x86_64-3.9/opentimelineview                                                           
  copying src/opentimelineview/track_widgets.py -> build/lib.linux-x86_64-3.9/opentimelineview                                                            
  copying src/opentimelineview/settings.py -> build/lib.linux-x86_64-3.9/opentimelineview                                                                 
  copying src/opentimelineview/__init__.py -> build/lib.linux-x86_64-3.9/opentimelineview                                                                 
  copying src/opentimelineview/console.py -> build/lib.linux-x86_64-3.9/opentimelineview                                                                  
  copying src/opentimelineview/ruler_widget.py -> build/lib.linux-x86_64-3.9/opentimelineview                                                             
  creating build/lib.linux-x86_64-3.9/opentimelineio_contrib                 
  copying contrib/opentimelineio_contrib/__init__.py -> build/lib.linux-x86_64-3.9/opentimelineio_contrib                                                 
  creating build/lib.linux-x86_64-3.9/opentimelineio_contrib/adapters        
  copying contrib/opentimelineio_contrib/adapters/extern_maya_sequencer.py -> build/lib.linux-x86_64-3.9/opentimelineio_contrib/adapters                  
  copying contrib/opentimelineio_contrib/adapters/extern_rv.py -> build/lib.linux-x86_64-3.9/opentimelineio_contrib/adapters                              
  copying contrib/opentimelineio_contrib/adapters/xges.py -> build/lib.linux-x86_64-3.9/opentimelineio_contrib/adapters                                   
  copying contrib/opentimelineio_contrib/adapters/advanced_authoring_format.py -> build/lib.linux-x86_64-3.9/opentimelineio_contrib/adapters              
  copying contrib/opentimelineio_contrib/adapters/ale.py -> build/lib.linux-x86_64-3.9/opentimelineio_contrib/adapters                                    
  copying contrib/opentimelineio_contrib/adapters/maya_sequencer.py -> build/lib.linux-x86_64-3.9/opentimelineio_contrib/adapters                         
  copying contrib/opentimelineio_contrib/adapters/burnins.py -> build/lib.linux-x86_64-3.9/opentimelineio_contrib/adapters                                
  copying contrib/opentimelineio_contrib/adapters/hls_playlist.py -> build/lib.linux-x86_64-3.9/opentimelineio_contrib/adapters                           
  copying contrib/opentimelineio_contrib/adapters/ffmpeg_burnins.py -> build/lib.linux-x86_64-3.9/opentimelineio_contrib/adapters                         
  copying contrib/opentimelineio_contrib/adapters/__init__.py -> build/lib.linux-x86_64-3.9/opentimelineio_contrib/adapters                               
  copying contrib/opentimelineio_contrib/adapters/fcpx_xml.py -> build/lib.linux-x86_64-3.9/opentimelineio_contrib/adapters                               
  copying contrib/opentimelineio_contrib/adapters/kdenlive.py -> build/lib.linux-x86_64-3.9/opentimelineio_contrib/adapters                               
  copying contrib/opentimelineio_contrib/adapters/rv.py -> build/lib.linux-x86_64-3.9/opentimelineio_contrib/adapters                                     
  creating build/lib.linux-x86_64-3.9/opentimelineio_contrib/adapters/aaf_adapter                                                                         
  copying contrib/opentimelineio_contrib/adapters/aaf_adapter/aaf_writer.py -> build/lib.linux-x86_64-3.9/opentimelineio_contrib/adapters/aaf_adapter     
  copying contrib/opentimelineio_contrib/adapters/aaf_adapter/__init__.py -> build/lib.linux-x86_64-3.9/opentimelineio_contrib/adapters/aaf_adapter       
  running egg_info                                                           
  writing OpenTimelineIO.egg-info/PKG-INFO                                   
  writing dependency_links to OpenTimelineIO.egg-info/dependency_links.txt   
  writing entry points to OpenTimelineIO.egg-info/entry_points.txt           
  writing requirements to OpenTimelineIO.egg-info/requires.txt               
  writing top-level names to OpenTimelineIO.egg-info/top_level.txt           
  reading manifest file 'OpenTimelineIO.egg-info/SOURCES.txt'                
  reading manifest template 'MANIFEST.in'                                    

**warning: no files found matching 'CHANGELOG.md'                            
  no previously-included directories found matching '.github'                
  no previously-included directories found matching 'docs'                   
  warning: no previously-included files found matching '.gitmodules'         
  warning: no previously-included files matching '*.git' found under directory 'src'                                                                      
  warning: no previously-included files found matching '.readthedocs.yml'    
  warning: no previously-included files found matching 'readthedocs-conda.yml'                                                                            
  warning: no previously-included files found matching '.codecov.yml'        
  warning: no previously-included files found matching '.gitlab-ci.yml'      
  warning: no previously-included files found matching '.travis.yml'         
  warning: no previously-included files found matching '*.pdf'               
  warning: no previously-included files found matching 'CODE_OF_CONDUCT.md'  
  warning: no previously-included files found matching 'CONTRIBUTING.md'     
  warning: no previously-included files found matching 'CONTRIBUTORS.md'     
  warning: no previously-included files found matching 'contrib/opentimelineio_contrib/adapters/Makefile'                                                 
  warning: no previously-included files found matching 'Makefile'            
  no previously-included directories found matching 'contrib/opentimelineio_contrib/adapters/tests'                                                       
  no previously-included directories found matching 'maintainers'            
  no previously-included directories found matching 'tests'                  
  no previously-included directories found matching 'src/deps/pybind11/tools/clang'                                                                       
  no previously-included directories found matching 'src/deps/rapidjson/thirdparty'**                                                                       

  adding license file 'LICENSE.txt'                                          
  adding license file 'NOTICE.txt'                                           
  writing manifest file 'OpenTimelineIO.egg-info/SOURCES.txt'                
  copying src/py-opentimelineio/opentimelineio/adapters/builtin_adapters.plugin_manifest.json -> build/lib.linux-x86_64-3.9/opentimelineio/adapters       
  creating build/lib.linux-x86_64-3.9/opentimelineio_contrib/application_plugins                                                                          
  creating build/lib.linux-x86_64-3.9/opentimelineio_contrib/application_plugins/rv                                                                       
  creating build/lib.linux-x86_64-3.9/opentimelineio_contrib/application_plugins/rv/example_otio_reader                                                   
  copying contrib/opentimelineio_contrib/application_plugins/rv/example_otio_reader/PACKAGE -> build/lib.linux-x86_64-3.9/opentimelineio_contrib/application_plugins/rv/example_otio_reader                                            
  copying contrib/opentimelineio_contrib/application_plugins/rv/example_otio_reader/example_otio_reader_plugin.py -> build/lib.linux-x86_64-3.9/opentimelineio_contrib/application_plugins/rv/example_otio_reader                      
  copying contrib/opentimelineio_contrib/application_plugins/rv/example_otio_reader/otio_reader.py -> build/lib.linux-x86_64-3.9/opentimelineio_contrib/application_plugins/rv/example_otio_reader                                     
  creating build/lib.linux-x86_64-3.9/opentimelineio_contrib/application_plugins/tests                                                                    
  copying contrib/opentimelineio_contrib/application_plugins/tests/__init__.py -> build/lib.linux-x86_64-3.9/opentimelineio_contrib/application_plugins/tests                                                                          
  copying contrib/opentimelineio_contrib/application_plugins/tests/test_rv_reader.py -> build/lib.linux-x86_64-3.9/opentimelineio_contrib/application_plugins/tests                                                                    
  copying contrib/opentimelineio_contrib/adapters/contrib_adapters.plugin_manifest.json -> build/lib.linux-x86_64-3.9/opentimelineio_contrib/adapters     
  running build_ext                                                          
  Traceback (most recent call last):                                         
    File "/tmp/pip-install-8o713fqk/opentimelineio_6c9debc12bb7443190382115f6a8c322/setup.py", line 171, in run                                           
      out = subprocess.check_output(['cmake', '--version'])                  
    File "/usr/lib/python3.9/subprocess.py", line 424, in check_output       
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,       
    File "/usr/lib/python3.9/subprocess.py", line 505, in run                
      with Popen(*popenargs, **kwargs) as process:                           
    File "/usr/lib/python3.9/subprocess.py", line 951, in __init__           
      self._execute_child(args, executable, preexec_fn, close_fds,           
    File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child    
      raise child_exception_type(errno_num, err_msg, err_filename)           
  **FileNotFoundError: [Errno 2] No such file or directory: 'cmake'**            
                                                                             
  During handling of the above exception, another exception occurred:        
                                                                             
  Traceback (most recent call last):                                         
    File "<string>", line 1, in <module>                                     
    File "/tmp/pip-install-8o713fqk/opentimelineio_6c9debc12bb7443190382115f6a8c322/setup.py", line 358, in <module>                                      
      setup(                                                                 
    File "/home/ishtar/.local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup                                                     
      return distutils.core.setup(**attrs)                                   
    File "/usr/lib/python3.9/distutils/core.py", line 148, in setup          
      dist.run_commands()                                                    
    File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands   
      self.run_command(cmd)                                                  
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command    
      cmd_obj.run()                                                          
    File "/home/ishtar/.local/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run                                                         
      self.run_command('build')                                              
    File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command     
      self.distribution.run_command(command)                                 
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command    
      cmd_obj.run()                                                          
    File "/usr/lib/python3.9/distutils/command/build.py", line 135, in run   
      self.run_command(cmd_name)                                             
    File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command     
      self.distribution.run_command(command)                                 
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command    
      cmd_obj.run()                                                          
    File "/tmp/pip-install-8o713fqk/opentimelineio_6c9debc12bb7443190382115f6a8c322/setup.py", line 173, in run                                           
      raise RuntimeError(                                                    
  **RuntimeError: CMake must be installed to build the following extensions: _opentimelineio, _opentime**                                                     
  ----------------------------------------                                   
**ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8o713fqk/opentimelineio_6c9debc12bb7443190382115f6a8c322/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8o713fqk/opentimelineio_6c9debc12bb7443190382115f6a8c322/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-b28f_5_6/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/ishtar/.local/include/python3.9/opentimelineio Check the logs for full command output.**

**Comment by meshula** [comment]
Is cmake in your path? I mean, if you type cmake does it run?

**Comment by cyborgbabe** [comment]
I'm not sure... when typing Cmake on the terminal it gives me this message

Usage

  cmake [options] <path-to-source>
  cmake [options] <path-to-existing-build>
  cmake [options] -S <path-to-source> -B <path-to-build>

Specify a source directory to (re-)generate a build system for it in the
current working directory.  Specify an existing build directory to
re-generate its build system.

Run 'cmake --help' for more information.

**Comment by cyborgbabe** [comment]
Hi again!! 

Cmake was actually not in my path, and after digging around a little bit I found this line of command 

> export PATH=~/usr/cmake-path/bin:$PATH

After which I was able to run 

> python3 -m pip install OpenTimelineIO 

It still gave out a lot of error messages like 

> ERROR: Command errored out with exit status 1:

and ultimately failed to build a wheel for OpentimelineIO, but in the end it successfully installed the program! Thank you Meshula for pointing that out and hope this helps anyone with a similar problem n.n

**Comment by meshula** [comment]
Glad you got a successful install :) I hope next time it goes more smoothly!
