### ISSUE TITLE
Rename Sequence to Track

### ISSUE THREAD

**Issue by jminor** [PixarAnimationStudios/OpenTimelineIO#112]
In discussion with some folks new to the project it has become clear that the term "Sequence" is sometimes confusing, and doesn't match the common terminology used when talking about timelines in practice. I would like to propose that we rename "Sequence" to "Track" (both the class name and in the file format).

The schema versioning mechanism should be able to accommodate this. Specifically, older .otio files with "Sequence.1" objects in them would be read into OTIO as Track objects and then serialized out again as "Track.1" without loss of any data.

If you have any opinions about this (pro or con), please comment.

**Comment by ssteinbach** [comment]
Addressed by #173
