### ISSUE TITLE
otioview scene rect clips items at the end of track

### ISSUE THREAD

**Issue by michdolan** [PixarAnimationStudios/OpenTimelineIO#1207]
### Incorrect Functionality and General Questions

When adding a new Stack to otioview, `frame_all` is run to scale the items in each track to fit the visible scene rect. The scaling function works well, but it doesn't seem to account for the width `TrackNameItem` adds to the scene. As a result, items toward the end of the track are clipped, so that when you are zoomed into the track (and sometimes upon the initial `frame_all` fit), scrolling right to see items at the end of the track is not possible, as they extend beyond the scroll area, and you must instead zoom out or widen the window to see them.

I dug into the code to investigate this, hoping it would be a simple fix (by adding `TRACK_NAME_WIDGET_WIDTH` to the initial scene rect calculation, for example), but the solution was more complicated since it must account for the various `counteract_zoom` implementations. What I did find was that if you modify these two lines in `track_widgets.py` (removing the `TrackNameItem` offset), the fit and scroll area are pixel perfect:

In `BaseItem.__init__`:
```
self.current_x_offset = TRACK_NAME_WIDGET_WIDTH
```
-> 
```
self.current_x_offset = 0
```

In `Track._populate`:
```
    track_name_rect = QtCore.QRectF(
        0,
        0,
        TRACK_NAME_WIDGET_WIDTH,
        TRACK_HEIGHT
    )
```
->
```
    track_name_rect = QtCore.QRectF(
        0,
        0,
        0,
        TRACK_HEIGHT
    )
```

Those won't work for fixing it of course, but confirmed my suspicion that the `TrackNameItem` was the underlying cause. I think long-term, the fix here would be to move the track names to a separate widget to the left of the timeline, which would also replicate the behavior of most non-linear editors where scrolling the timeline doesn't effect the track list. Short-term, this could probably be resolved with some tweaks to the sizing math, but those tweaks felt non-trivial at first glance.

## To Reproduce

I'm seeing this on: Windows 10, Python 3.7, OTIO 0.14

To reproduce, open a timeline in otioview, and reduce the window size (or move the splitter left) so that the horizontal scroll bar appears. Scroll this to the right. You shouldn't be able to see all the items at the end of the track. The width of the clipped area is about equivalent to the track name item width.

**Comment by michdolan** [comment]
I found a simple solution. My initial thought of accounting for `TRACK_NAME_WIDGET_WIDTH` in `_adjust_scene_size` was correct, but I needed to scale that with `CURRENT_ZOOM_LEVEL`  and call `_adjust_scene_size` whenever the zoom level changes. Doing that, the scene rect width adjusts to the scaled items and matches the active width of the track.

I'll submit a PR with a fix. I'll need to get a CCLA signed before the EasyCLA check will pass, which may take a week or two, but I'll get that started this week.

**Comment by michdolan** [comment]
This is fixed in my branch, which I'll open a PR for when I can:
https://github.com/michdolan/OpenTimelineIO/tree/otioview_track_fit

**Comment by meshula** [comment]
@michdolan Did you attempt the EasyCLA system?

**Comment by michdolan** [comment]
Yes, I have a CCLA approved now. I'll open the PR with this fix today.
