### ISSUE TITLE
Guard mac universal builds

### ISSUE THREAD

**Issue by meshula** [PixarAnimationStudios/OpenTimelineIO#1244]
## Bug Report

https://github.com/PixarAnimationStudios/OpenTimelineIO/pull/1214 introduces a default to do universal binary builds on macOS. This is a fantastic addition, but of course, building for M1 is not possible on OS < 10.15. vfxplatform specifies support for 10.13 in CY2021, and since OTIO supports the current vfxplatform year, and the three preceding, we are stuck with 10.13 until the year 2025. In practice, I don't think we will be able to support 10.13 that long, but for this year at least, we should expect that there are still users on 10.13.

Due to the complication of creating python wheels, I'm not sure how to structure things to make this allowance practical, so this is a request for help on how to approach this.

**Comment by reinecke** [comment]
We'd welcome a PR on this, but we don't currently plan to address it.

**Comment by meshula** [comment]
Will reopen if necessary.
