### ISSUE TITLE
Shotgun Integration

### ISSUE THREAD

**Issue by ssteinbach** [PixarAnimationStudios/OpenTimelineIO#138]
Several studios have asked about integration with Shotgun, so we are tracking this request with this issue here.

**Comment by zebulon75018** [comment]
Hello, I'm interesting to work on , and to help you about this. 
I have already do bridge between EDL / shotgun.  ( entity cuts / cut , shot ... )
Are you interesting to my proposition , how can we processed ? I'll open a sg acount , have you more detail about the work to do ( is it a bridge to be done ). So Let me know...

**Comment by jhodges10** [comment]
@zebulon75018 you should join the ASWF Slack org and see if you can speak with anyone from Autodesk there. I know that they tend to join the TSC meetings. I also have a sneaking suspicion that they're already planning on using OTIO to revamp this [Feature](https://portal.productboard.com/9yfnzm5dxd3vzwducxczpphv/c/69-better-workflows-for-cut-importing?utm_medium=social&utm_source=portal_share) on their roadmap.

**Comment by eidmi** [comment]
@zebulon75018, we (Autodesk) are part of the TSC and would love to hear more about your current bridge to Shotgun and related workflows... And yes ;-) we're currently using internally OTIO in Shotgun. Thanks.

**Comment by zebulon75018** [comment]
@eidmi hi , could we discuss by email my email is zebulon75018( __at__ ) yahoo ( __dot__ ) fr 
is it correct for you ?  or I m also on slask and you ?
I m waiting your email...

**Comment by meshula** [comment]
Shotgun is now Shotgrid. If there's a need to track Shotgrid integration please open a new issue.
