### ISSUE TITLE
Make the Travis Repository Public

### ISSUE THREAD

**Issue by ssteinbach** [PixarAnimationStudios/OpenTimelineIO#146]
Looks like this didn't make the transfer to being public.  Sorry about that!

**Comment by jminor** [comment]
Hey @alexwidener can you see the Travis build status now?

**Comment by alexwidener** [comment]
Nah, still "Can't Find"

https://travis-ci.com/PixarAnimationStudios/OpenTimelineIO/

![image](https://user-images.githubusercontent.com/3489076/29191352-75836df6-7deb-11e7-946e-3b8ed397ab31.png)

**Comment by mikemahony** [comment]
@alexanderwilkie Can you see it if you click on the ![image](https://user-images.githubusercontent.com/1740063/29192124-02f94df2-7dd5-11e7-93e1-5bc5a2d196fd.png) in the [README](https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/master/README.md)?

**Comment by alexwidener** [comment]
I can see it when I click that, yes.

**Comment by jminor** [comment]
FYI, you'll see it under travis-ci.ORG but not travis-ci.COM now that it is public.

**Comment by alexwidener** [comment]
Okay, that makes sense - the links that are inside of my original merge request #144 (the X and check marks) still say .com and don't work - they're just left behind from the private era. I'd assume any future builds in MRs will now be public. We'll see in a couple days :)

Thanks :)
