### ISSUE TITLE
Round-tripping does not appear to be working with FCP XML

### ISSUE THREAD

**Issue by alexwidener** [PixarAnimationStudios/OpenTimelineIO#149]
Hello again, 

So I've written a Premiere extension to export out of PPro to the OTIO file, and then import that same OTIO file. 

It does what I've mentioned in my e-mail to Josh and Stephan previously of: 
 1 ) Export out of PPro API via FCP XML
 2 ) Use OpenTimelineIO to convert the file data to the OTIO standard
 3 ) Have an OTIO file to pass along

and inversely: 
 1 ) Select the OTIO file to import
 2 ) Use OpenTimelineIO to convert the OTIO file data to FCP XML (or ideally any format that is supported that can import - but that's not on my slate right now)
 3 ) Use PPro API to import the temp FCP XML.

So, what I'm seeing is that I can't import the 'temp' FCP XML in the second set, and looking at the files, you can see that there's a substantial difference between them. 

[The full XML Premiere exports via the API](https://gist.github.com/alexwidener/63c9d4f8f7bca48c3e5441326ae8ce69)

[The OTIO file generated by OpenTimelineIO](https://gist.github.com/alexwidener/3d8ea39a9816ecba80491f55573d9898)

[and the FCP written by the Adapter which should import but does not parse](https://gist.github.com/alexwidener/71e08bb592058a7095a1e29c64d9b08b)

Results in : 

![image](https://user-images.githubusercontent.com/3489076/29745729-2786be34-8a91-11e7-8a73-5acc64415135.png)

So, as you can (hopefully) see - there's a bit of discrepancy between the full XML file and OpenTimelineIO's XML file - I'm going to dig into it further, but wanted to get your eyes on it to see if you knew more about it. 

It may be worth nothing that there's no actual _media_ in the sequence that was exported, it was purely the Bars and Tone filler - I'm going to try with actual media as well.

**Comment by ssteinbach** [comment]
Ah.  So the bars and tone specifically I think we would eventually support via generators (see: #148).  We haven't landed that PR yet, and once we do support in the FCP7 XML adapter would need to be added.  That might be related to the issue?

**Comment by alexwidener** [comment]
Then I'll definitely do some testing with actual media in a little bit and report back. I hope that's the case! :)

**Comment by ssteinbach** [comment]
Thanks for taking a look!  Great to have people looking around.  And if you have opinions about how it should be implemented, let us know what you think of #148 !

**Comment by alexwidener** [comment]
Confirmed, looks like it's working just fine round-trip with standard media. 

Looks like I'll need to look into #148 :) 

I'll go ahead and close this issue.
