### ISSUE TITLE
HLS Playlist Adapter

### ISSUE THREAD

**Issue by reinecke** [PixarAnimationStudios/OpenTimelineIO#15]
Create an adapter that expresses Fragments or Segments as clips in a sequence to allow authoring of HLS playlists from OpenTimelineIO.

**Comment by vectronic** [comment]
Hello,

This is probably just background noise for you, but I wanted to comment/query on this item as it relates to something I've been working on.

I have been looking at rendering out CPL proxies to HLS packages where the individual track clips (resources) in the CPL are marked with discontinuities in the HLS playlist.

I realised the issue with this approach is that with a master playlist referencing a separate audio and video media playlist is that the HLS standard and players expect to be able to sync the media across audio and video based on the discontinuity sequence number.

As an open timeline structure does not necessarily have synced edit points across audio and video, I believe you would run into the same problem when outputting a master HLS referencing separate audio and video media playlists with non-synced discontinuities.

I am wondering if you have seen this, thought about this or indeed can correct my understanding on this issue?

Regardless, thanks for the great project.

Nick

**Comment by reinecke** [comment]
Hey Nick,

Welcome to OTIO! This kind of discussion is probably best suited for our [Google Group](https://groups.google.com/forum/#!forum/open-timeline-io), but I'm happy to answer here.

To clarify I'm understanding, you have an IMF CPL that is referencing assets from within an IMP (J2K MXF essence I would guess?). I'd presume you've also transcoded these essences into either fmp4 or ts proxies for streaming. Are you looking to use the CPL to build a timeline that can export to HLS and stream the proper assembly of your Composition?

I think it's really interesting use case.

Considering this otioview visualzation of Apple's bip bop example:
![image](https://user-images.githubusercontent.com/1649087/59471917-7b7dfd80-8df1-11e9-87a1-9493963fffe1.png)

In the OTIO model, each clip is a media segment. You can see that the audio and video (roughly) align (this is to facilitate efficient seeking). CPL Segments (I think) can have unaligned resources within a given Sequence, but the segments align. As far as I know, within HLS you don't actually have to have segments align in any way, it just affects seek performance when they don't. I think you could pretty directly map these concepts across (assuming your proxies have IDR frames and segment breaks in the right places). I don't think there would be a need for `EXT-X-DISCONTINUITY` tags either, I think those are mostly intended for use cases where a live stream has a blank out and you need to skip some of your HLS sequence numbers, I don't think it should be needed in an on-demand playlist.

If you can share a more concrete example (preferably over on the google group), I'd be happy to try working through it with you a bit more. Incidentally, we've talked about doing a CPL adapter, but it hasn't quite bubbled up in our priorities yet.

-Eric
