### ISSUE TITLE
Validation utility

### ISSUE THREAD

**Issue by jminor** [PixarAnimationStudios/OpenTimelineIO#154]
OTIO should have a validation utility that reads an OTIO file (or anything via an adapter) and then produces a brief report. The report tells you if the file was parsed correctly or not, to discover invalid inputs, and also tells you a bit about the structure and contents of what it found. It should highlight any unexpected, unsupported, or out dated schemas.

**Comment by ssteinbach** [comment]
Initially Addressed by #164.  We're sure this will draw more features over time.
