### ISSUE TITLE
opentime defaults to 1fps, disagreeing with documentation

### ISSUE THREAD

**Issue by meshula** [PixarAnimationStudios/OpenTimelineIO#155]
In opentime.py we read

````
"""Library for expressing and transforming time.

Defaults to 24 fps, but allows the caller to specify an override.
"""
````

however in the code we read:
````
class RationalTime(object):
    """ Represents an instantaneous point in time, value * (1/rate) seconds
    from time 0seconds.
    """

    def __init__(self, value=0, rate=1):
        self.value = value
        self.rate = rate
````

I prefer the default rate is 1, as the code implements.

Later, we read:

````
def from_timecode(timecode_str, rate=24.0):
````
which is inconsistent. TBH I'd much rather have rate be 1 here too. 24fps is of particular interest to film, but not to other domains.

So I would suggest that the default rate be consistently 1.

**Comment by jminor** [comment]
You're right that the documentation is incorrect. I'll fix that.

A rate of 1 doesn't make sense for timecode. I think we should remove the `rate=24` default value from `from_timecode` and require the caller to specify the rate they expect. You can really only know that from context.

As much as possible, we should remove any assumptions about frame rate from OTIO to ensure that it is flexible.

**Comment by meshula** [comment]
Removing the default works for me!

**Comment by jminor** [comment]
Fixed.
