### ISSUE TITLE
Is TimeRange [start, end)?

### ISSUE THREAD

**Issue by meshula** [PixarAnimationStudios/OpenTimelineIO#156]
If I have a number of TimeRanges that I wish to abut on a timeline perfectly adjacently, at a frame rate of 1.0, I assume this is conceptually legit:

start = TimeRange(RationalTime(0, 1), 0.2)
a = TimeRange(RationalTime(0.2, 1), 1)
b = TimeRange(RationalTime(1.2, 1), 1)
c = TimeRange(RationalTime(2.2, 1), 1)
...

That's good, right?

**Comment by jminor** [comment]
A TimeRange is made of two RationalTimes (start_time and duration), like this:

```
r = TimeRange(RationalTime(0,1), RationalTime(0.2,1))
```

You can access the inclusive or exclusive end time from a TimeRange via `end_time_inclusive` and `end_time_exclusive`.

To make two TimeRanges adjacent do this:
```
r1 = TimeRange(RationalTime(0,1), RationalTime(0.3,1))
r2 = TimeRange(r1.end_time_exclusive(), RationalTime(0.4,1))
```

See the examples in the `test_opentime.py` test case for details:
https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/master/tests/test_opentime.py

**Comment by jminor** [comment]
@meshula, I added a test case that illustrates adjacent TimeRanges: https://github.com/PixarAnimationStudios/OpenTimelineIO/pull/159

Does that help?

Also, we'd like to find the point where you were led astray with the 2nd parameter to the TimeRange constructor so we can fix the documentation or something to help others in the future. Do you recall when/why you made that assumption?

**Comment by meshula** [comment]
This new test case totally helps!

https://github.com/PixarAnimationStudios/OpenTimelineIO/pull/159/commits/862629db78464c4c90e6064e86e764a3efe71f4b

As to what led me astray, I think I wrote that code before I read the OTIO implementation, and it happened to work (or did what I expected it to do, for the wrong reasons). I think it simply didn't occur to me that duration on the TimeRange would also be a RationalTime. It is obvious in retrospect, my only excuse is coding with a beer in hand and/or after midnight :)
