### ISSUE TITLE
EDL clip names as reel names

### ISSUE THREAD

**Issue by tin2tin** [PixarAnimationStudios/OpenTimelineIO#168]
Clip names are often written/read(ex. Lwks, Flowblade, ShotCut and Blender) as reel names in EDL files like this(case sensitive):
```
001 4388aaBB V C 05:04:46:13 05:04:56:03 01:03:16:04 01:03:25:19
* FROM CLIP NAME: 4388aaBB.dpx
```
[NB. spacing is truncated in example. File name as Reel name is case sensitive(in Lwks), 8 characters long, no empty space characters in file name(Blender) and with no extention]
Looking through the OTIO EDL code, this practice seems to be ignored i/o in EDL files. 

[Btw. really great project. Hopefully, the open source A/V projects will embrace it. If ex. MLT was added as a format then Kdenlive, ShotCut, and Flowblade could all benefit from it. It would also be great to see Blender, Ardour, Audacity, Synfig, FFmpeg, OpenToonz, Storyboarder etc. sharing projects with Lwks, Resolve, Premiere, Final Cut and Avid and vice versa. ]

**Comment by jminor** [comment]
You're right, the EDL adapter doesn't really pay much attention to the reel, which is an oversight. In the case you mention, it appears to be also covered by `FROM CLIP NAME`. If the EDL output from the adapter put the truncated/abbreviated clip name into the reel would that be sufficient, or does it need to read the reel name and carry that around too?

**Comment by tin2tin** [comment]
"* From clip name: " is an addition to the original CMX 3600 EDL format. Ex. Lwks and Blender can't parse these comment lines, so the only way is to use the reel name to identify the files in those softwares. But I think most pro NLE's will look in the comments for a file-name with extension, after "* From clip name:". I know Resolve will do that if you check the right boxes for the import settings. I don't know which NLEs will use the full path "* From file:", though that would be the logic - I haven't tested those. 

If you can provide a short OTIO edl file and a video clip with cuts at the same frames as there are cuts in the video clip I can test it against Resolve, Blender and Lwks. [Like I did for ShotCut: https://forum.shotcut.org/t/mlt2edl-script-error-fix/55/40]

**Comment by mikemahony** [comment]
Does https://github.com/PixarAnimationStudios/OpenTimelineIO/pull/200 address this issue? We set `clip.metadata['cmx_3600']['reel']` to the clip name before exporting an EDL so that it may be read and displayed by our 3rd party mastering suite.

**Comment by tin2tin** [comment]
@mikemahony - Have these things been taken into consideration of the fix for reading/writing reel-names in EDL-files? 
- They are case sensitive
- No space characters in file-name(maybe swap with '_'?)
- Always 8 characters long(insert empties so the number of characters matches 8)
- No file extension on reel name

Alternatively can you upload an exported edl file I can have a look at?

[NB. in older import parsers like the one in Lwks, reel names and time codes are only read from file embedded reel-names and time codes. So that might give some odd results if the parsers can't be forced to use file name from comments and starting time codes at file start. Alternatively a parcer would have to read and use file embedded reel names and timecodes. ffmpeg can do that. However as far as aI know, only Lwks is limited to embedded values]

**Comment by jminor** [comment]
We recently introduced a keyword argument for the EDL `write_to_string()` function that lets you pick a `style` for the EDL. This is to support variation in the format for cases like this.

@mikemahony's change #200 makes this easier to add, but doesn't cover the specific formatting you mentioned. It does, however, preserve the reel when reading an EDL and writing back to an EDL, which might help.

There are some sample EDLs that are part of the unit tests for OTIO here: https://github.com/PixarAnimationStudios/OpenTimelineIO/tree/master/tests/sample_data

@tin2tin are you able to do a little bit of Python coding on this? I think what you're asking for would be pretty easy to add to the `_reel_from_clip()` function here: https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/master/opentimelineio/adapters/cmx_3600.py#L876

**Comment by tin2tin** [comment]
I'm sorry, I'm not much of a coder(I'm a director). My knowledge of the EDL format comes from testing the edl export implementations of Shotcut, Flowblade and Blender against EDL import in Davinci Resolve, Lightworks and Blender. 
[https://forum.shotcut.org/t/mlt2edl-script-error-fix/55/16](https://forum.shotcut.org/t/mlt2edl-script-error-fix/55/16)
[https://github.com/jliljebl/flowblade/issues/252](https://github.com/jliljebl/flowblade/issues/252)

I had a look at the samples. Some of them do not respect the 8 characters wide column(ex. the dissolve examples) for the reel names, so these will not be imported into ex. Lwks. And some include extensions in the filenames. I have never seen those before. Try to run those files in EDLtoolkit and see how the files are corrected. And maybe add app name to the example files so it is easier to locate differences in the format? 

A few examples:
[EDL_EX.zip](https://github.com/PixarAnimationStudios/OpenTimelineIO/files/1608584/EDL_EX.zip)

Someone uploaded this Premiere edl export for me(it has a lot of selectable options for including in edl files): 
[https://forum.shotcut.org/uploads/default/original/2X/8/8a8d7c96d6f45b85688531e8b4dd4529d4628c1e.edl](https://forum.shotcut.org/uploads/default/original/2X/8/8a8d7c96d6f45b85688531e8b4dd4529d4628c1e.edl)

**Comment by jminor** [comment]
Thanks for the details and examples. We will take a closer look to make sure OTIO can parse these or at least give clear error messages about what it has trouble with. If you'd like us to include these as official test cases in the project, we'll need a CLA from you: https://github.com/PixarAnimationStudios/OpenTimelineIO/wiki/Contributing

The EDL adapter can certainly grow to accommodate some variation in the format, but it probably won't ever become a perfect translator for every flavor of EDL.

Longer term, we'd like to encourage these other applications to move away from EDL and use OTIO as an interchange format instead. If you have contacts in the communities for these other applications, can you help to let them know about OTIO?

**Comment by tin2tin** [comment]
I think 8 characters in reel names is a standart, however some exporters go up to 32 characters. But to keep it fail safe I would recommend 8 characters. 

The files are found around the interwebs. So I don't have any rights for them, but I guess if the file names are changed, no one would have any trouble with you using them any way you want.

The trouble with most opensource projects are the lack of man-power and that is there always goes into the core functionality, so spending time on getting files into other softwares is not prioritized ex.:
https://community.ardour.org/node/13913

However when the fcpxml and aaf i/o in otio has matured, I suspect they eventually will priotize an interchange format like this(if their license comply). But I think if you guys would approach them with the power of Pixar in the back, they would pay more attention.

**Comment by apetrynet** [comment]
Hi!
I ran into this "limitation" today when going from xml to and edl via otioconvert and thought I'd add my two cents.
Quite a few applications base clip names on the reel name and in those cases `AX` make them hard to conform and so on.

I prefer when reel names are the same as `FROM CLIP NAME`, but to be safe it makes sense to keep reel names to 8 characters like the original spec. (optional perhaps?)

What we could do is something similar to what FCP7 did/does, which is to truncate the reel name to spec and add a comment letting people know what they did. 
From an FCP7 EDL: `FINAL CUT PRO REEL: YL600_COMP_MASTER_V001_TMA REPLACED BY: YL600COM`

FCP's comment is a bit strange not prefixing the line with an `*` so I don't suggest copying this directly. We could however create our own comment which follows the `*` convention and informs users of the truncation like: `* OTIO BASED REEL NAME ON: YL600_COMP_MASTER_V001_TMA` and `clip.metadata['cmx_3600']['reel']` then yields: `YL600COM`

The resulting lines in an EDL:
```
453  YL600COM V     C        14:09:34:07 14:09:40:18 02:14:49:09 02:14:55:20  
* FROM CLIP NAME:  YL600_COMP_MASTER_V001_TMA_PRORES
* OTIO BASED REEL NAME ON: YL600_COMP_MASTER_V001_TMA_PRORES
```
Please let me know if none of this makes any sense and I'll try to express myself clearer.

I can try to implement this (or another) solution if you like.

**Comment by jminor** [comment]
@apetrynet feel free to change the reel name based on the clip name. The hard coded "AX" was based on our limited EDL experience. There is a `style` parameter to the adapter which could be used to control the specifics if needed, but I doubt that anyone really needs the AX reel name.

**Comment by apetrynet** [comment]
Cool!
Should I add some logic revolving truncating reel name as well? Could be a `trunc_reelname=True` or `strict_reelname=True` argument in the `write_to_string()` for instance?

**Comment by apetrynet** [comment]
Hi!

I began working on this and have a first implementation in place, but need to tweak some of the unit tests to support the new reel names.
The tests checking against a string representation of an EDL are OK, but I'm having some difficulties deciding how to approach the `test_edl_round_trip_mem2disk2mem` which compares JSONs. 
They won't be equal anymore since I've added a comment and reel name to the clips metadata. 

I can of course get rid of those metadata entries, but find them a bit useful. Has anyone got any thoughts on this?
I haven't created a PR yet, but have a [fetaure branch](https://github.com/apetrynet/OpenTimelineIO/tree/edl_reelnames) setup.

**Comment by tin2tin** [comment]
I would just like to add that I've noticed the Davinci Resolve edl export adds the full file name no matter the number of characters, so if the normal 8 characters limit can't be read succesfully - then maybe the parts before and after the name could be cut because the length of those should be a consisten number of characters.  

Ex.
`001  WildlifeInAfrica V     C        00:00:00:00 00:00:04:05 00:00:00:01 00:00:04:06`

**Comment by jminor** [comment]
We'd like OTIO to be flexible in reading EDLs that don't 100% match these limitations, since there is quite a lot of variation out there. When writing an EDL out from OTIO, there is an optional "flavor" argument to the EDL adapter to help with differences like this. Ideally the reader won't need an argument, but could discover it from the file itself.

**Comment by apetrynet** [comment]
@tin2tin My proposed changes don't touch the reel name when reading an EDL. It adds it to the metadata and goes on with it's business, so the adapter should be able to read an EDL from DaVinci. The truncate option is for writing EDLs.
@jminor Was your last comment aimed at my code or @tin2tin's comment? 
I'll submit a  [WIP] PR.

Thanks!

**Comment by jminor** [comment]
My comment above was mostly related to @tin2tin's comment about Resolve, and to just point out the "flavor" concept. I'll take a look at the PR :)

**Comment by mikekoetter** [comment]
Hello all, I just pushed up a PR ( #434 ) to that does some work on the cmx_3600 adapter

Although this PR doesn't address much (if any) of the direct concerns mentioned here it does work to maintain the SOURCE_ID (reel) when round tripping an EDL

My thinking is if we are maintaining and storing the reel in the metadata one could easily add a hook to truncate/clean/substitute reel names or clip names.  That is where we are doing our path mapping between Linux and Windows as well

**Comment by apetrynet** [comment]
@ssteinbach I guess we can close this with #434 and #392 merged into master?

**Comment by ssteinbach** [comment]
Yes ! I was hunting around for this issue.  Thanks!
