### ISSUE TITLE
FCP adaptor using file timebase instead of clipitem 

### ISSUE THREAD

**Issue by al3ph** [PixarAnimationStudios/OpenTimelineIO#174]
Noticed this when using audio clips which have a clipitem timebase of 24, and a file timebase of 30, but when viewing in otioview.py the clip is too short, it looks like its using end/30fps instead of 24fps.

					<masterclipid>masterclip-10</masterclipid>
						<name>tumbl-105.0-171013.DX_MIX.aif</name>
						<enabled>TRUE</enabled>
						<duration>5912</duration>
						<rate>
							<timebase>24</timebase>
							<ntsc>FALSE</ntsc>
						</rate>
						<start>0</start>
						<end>755</end>
						<in>0</in>
						<out>755</out>

                        "source_range": {
                            "OTIO_SCHEMA": "TimeRange.1", 
                            "duration": {
                                "OTIO_SCHEMA": "RationalTime.1", 
                                "rate": 29.97, 
                                "value": 755
                            }, 
                            "start_time": {
                                "OTIO_SCHEMA": "RationalTime.1", 
                                "rate": 29.97, 
                                "value": 0
                            }
                        }

I can supply an example if needed..

ta

**Comment by al3ph** [comment]
Here we go, it's using the media framerate instead of the item framerate when setting the source_range.

def _parse_clip_item(clip_item, transition_offsets, element_map):
    markers = clip_item.findall('./marker')

    media_reference = _parse_media_reference(
        clip_item.find('./file'),
        element_map
    )

   src_rate = _parse_rate(clip_item.find('./file'), element_map)

**Comment by jminor** [comment]
@al3ph can you confirm that @bashesenaxis's PR #177 fixes the issue you found?

**Comment by alatdneg** [comment]
Worked it out, yup that did the trick cheers!

**Comment by alatdneg** [comment]
Not sure if writing out the xml works though(I suspect that'll have the same kind of problem), as I only tested reading xml..
