### ISSUE TITLE
EDL adapter with frame rate hardcoded

### ISSUE THREAD

**Issue by tuan-huy-truong** [PixarAnimationStudios/OpenTimelineIO#182]
Hi everybody, we need to be able to parse edl at different frame rates. I tried to code something but it seems that i failed for now, i will continue to search a proper way to do it but maybe some of you will hint me with a best practice putting it together.

Thanks.

**Comment by jminor** [comment]
Thanks for the fix :)

**Comment by tuan-huy-truong** [comment]
My pleasure :)
