### ISSUE TITLE
CI builds should run the AAF tests also

### ISSUE THREAD

**Issue by ssteinbach** [PixarAnimationStudios/OpenTimelineIO#202]
We need to configure Travis to install the AAF SDK and PyAAF, with specific versions of each.
Ideally this would be a separate build so we don't need to wait on it every time.

**Comment by markreidvfx** [comment]
I've updated PyAAF 1.0 release to include [manylinux](https://github.com/pypa/manylinux) wheels.
https://github.com/markreidvfx/pyaaf/releases
They should work hopefully work in Travis and include the AAF SDK.

**Comment by jminor** [comment]
Thanks @markreidvfx for the wheels and @mikemahony for the Travis leg work.
Addressed by #229
