### ISSUE TITLE
schema.track.neighbors_of is ambiguous as to order of neighbors

### ISSUE THREAD

**Issue by ssteinbach** [PixarAnimationStudios/OpenTimelineIO#211]
If you don't have neighbors of expand transitions, then its return value is ambiguous as to whether the return value is before or after.  Instead, return None if the neighbor doesn't exist.

Examples (assume all are clips):
```
[A, B, C] :: neighbors_of(B) -> (A, C)
[A, B, C] :: neighbors_of(A) -> (None, B)
[A, B, C] :: neighbors_of(C) -> (B, None)
[A] :: neighbors_of(A) -> (None, None)
```
In other words, it always should always return `(previous or None, next or None)`.  In the case of expanded transitions it would return `(previous or Gap, next or Gap)`.

Right now the last one for example returns `(A)` which is not particularly helpful.

**Comment by jminor** [comment]
Fixed in #212
