### ISSUE TITLE
Composition should not allow instanced children

### ISSUE THREAD

**Issue by jminor** [PixarAnimationStudios/OpenTimelineIO#224]
It is easy to accidentally add the same clip to a track multiple times, which leads to incorrect and confusing results. Composition should check for this and throw an exception when you try to insert the same child object multiple times.

Also the test_instancing() test should be updated to verify that instancing is not allowed. Currently it does the opposite. https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/master/tests/test_composition.py#L610

**Comment by ssteinbach** [comment]
Addressed by #257
