### ISSUE TITLE
Convenience for creating/adding a Gap, black, etc.

### ISSUE THREAD

**Issue by jminor** [PixarAnimationStudios/OpenTimelineIO#226]
Making a new Gap, or adding one to a Track, should be simpler. Same for adding a solid black clip.

Maybe something like: `gap = otio.schema.Gap(duration=otio.opentime.RationalTime(10, 24))`
or `slug = otio.make_solid_clip(color='black', duration=otio.opentime.RationalTime(10, 24))`

**Comment by ssteinbach** [comment]
Addressed by #286
