### ISSUE TITLE
Investigate whether types in otio.schema should be treated like reference types rather than value types

### ISSUE THREAD

**Issue by ssteinbach** [PixarAnimationStudios/OpenTimelineIO#228]
Currently all the types in OTIO are designed to be Value types.  However, we've hit a number of places where its starting to feel like it would make more sense to move the types in OTIO.Schema (ones deriving from `SerializableObject`) should be treated like reference types rather than value types.  This would mean that the default `==` operator would test pointer equivalency rather than value equivalency, and we would add a method `equivalent_to` to the objects to test value equivalency.

This would clean up issues like #222 because the built in `.index()` method from `collections.MutableSequence` would use the reference equivalency instead of value equivalency to find the object in the sequence.

It would also potentially help clarify the behavior around instancing and adding multiple things to the same sequence (#224).

This change would break backwards compatibility.

**Comment by reinecke** [comment]
I think this is a really solid idea. Given that there are a wide range of things that can be represented with schema types, the semantic meaning of whether or not two things are "equal" is somewhat fuzzy anyway.

**Comment by ssteinbach** [comment]
Addressed by #257
