### ISSUE TITLE
Put OTIO on PyPi

### ISSUE THREAD

**Issue by swallitsch** [PixarAnimationStudios/OpenTimelineIO#239]
It'd be great if we could install OTIO from pypi with pip.

This will require `setup.py` to have some additional fields such as `license`, `classifiers`, `keywords`, `platforms`. Because we're using a `README.md` markdown file, we'll also need a `setup.cfg` file to tell pypi where our long description is.

Once the setup.py work is complete, we can start uploading to PyPi.

[This is a good general article on getting your package ready for uploading to PyPi](http://peterdowns.com/posts/first-time-with-pypi.html) but it's upload section should not be used!

[This how to is good for everything after Register for PyPi](https://blog.jetbrains.com/pycharm/2017/05/how-to-publish-your-package-on-pypi/)

**Comment by swallitsch** [comment]
I'll be submitting a PR for updating setup.py

**Comment by swallitsch** [comment]
I've opened a PR (#241) which should contain the ground work needed to begin putting OTIO on PyPi. 

One thing to note as we move forward with this is that [Warehouse, the all new pypi, is now in Beta](http://pyfound.blogspot.com/2018/03/warehouse-all-new-pypi-is-now-in-beta.html), so PyPi deployment steps should be tested against that as well.

**Comment by ssteinbach** [comment]
This is now done:
https://pypi.org/project/OpenTimelineIO/

We've also updated our internal release process to include PyPI.
