### ISSUE TITLE
fcp_xml adapter doesn't seem to export offline/unreferenced clips correctly

### ISSUE THREAD

**Issue by apetrynet** [PixarAnimationStudios/OpenTimelineIO#265]
When exporting an XML with offline/unreferenced clips, OTIO should provide all tags needed to recreate those clips in an application even though some tags remain "empty". Currently the `_build_clip_item_without_media` function doesn't include the `<name>`, `<duration>`, `<pathurl>` and `<timecode>` tags in the `<clipitem> -> <file>` tag which results in the clip not getting created.

I like the explicitness of a call to `_build_clip_item_without_media`, but is it really necessary to differentiate the creation of an "online" or "offline" clip other than the `<pathurl>` being empty?  All other data should be in place if it's a clip placed in a timeline should it not?

Please note that I only tested import of such an XML in Hiero.

**Comment by ssteinbach** [comment]
@bashesenaxis Do you have any thoughts on this?

**Comment by bashesenaxis** [comment]
The idea behind `_build_clip_item_without_media` is that it deals with title objects. So they would never have any media.
For example:
https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/master/tests/sample_data/premiere_example.xml#L688
In this case, `<clipitem> -> <file> -> <name>` is identical to `<clipitem> -> <name>`, the `<duration>` wouldn't have any meaningful information and there would not be a `<parthurl>` associated with it either.

I am not entirely sure whether this is a premiere specific way of doing things.

**Comment by apetrynet** [comment]
Closing this one as it's really old and I haven't had use for this since the hiero plugin came to life.
Feel free to reopen if someone finds it useful.
