### ISSUE TITLE
Writing an integration of OTIO for Hiero

### ISSUE THREAD

**Issue by apetrynet** [PixarAnimationStudios/OpenTimelineIO#266]
Hi!

Just want to inform you that I'm in the process of writing support for importing and exporting OTIO files in Hiero.
At the moment I have the bare bones for export in place.
The exporter is available as one of the outputs in the export sequence dialog.
The importer I want to integrate alongside the import EDL/XML menu items.
 
If this is of interest where should I place the module in the folder structure? 
The integration consists of a few files so leaving it in the root of opentimelineio_contrib->adapters seems a bit messy. Also, since this is something that runs in Hiero does it even count as an adapter at all?

Thanks!

**Comment by ssteinbach** [comment]
Great!  I think a great place to put it would be:
`opentimelineio_contrib/application_plugins/<appname>`

If it is called through the adapter interface, it could be an adapter.  But if its a freestanding python script that calls OTIO and then does its own processing separate from that, which is what it sounds like you're describing, then it doesn't sound like an adapter to me.

Maybe you could also include a README.md in that directory that describes how to install the plugin?

**Comment by apetrynet** [comment]
Cool!
I'll add instructions in a README.md yes.

**Comment by apetrynet** [comment]
Hey!
I just pushed the first version of the Hiero exporter in my own [repo](https://github.com/apetrynet/OpenTimelineIO/tree/hiero_plugin/opentimelineio_contrib/application_plugins/hiero). It would be cool if someone could give it a spin and see if it works outside of my environment. I'll be working on an importer as well when I get some time for it.
Please give feedback and report issues in my repo to begin with (or no?)
Thanks!

**Comment by apetrynet** [comment]
Initial OTIO Import for Hiero is pushed.

**Comment by ssteinbach** [comment]
@apetrynet If you open a pull request then that gives people better visibility to it (as well as easy instructions for trying it out).  Our pattern at this point is to prefix the PR title with [WIP] (which gets removed when its ready to be accepted), but that way we can keep track of who is doing what.  Would you be up for giving that process a try?

**Comment by ssteinbach** [comment]
You can see examples of this right now, all the remaining PRs are `[WIP]`

**Comment by apetrynet** [comment]
Cool! I'll do it shortly.

**Comment by apetrynet** [comment]
Closing this ticket as I've created a PR #284
