### ISSUE TITLE
MLT XML adapter

### ISSUE THREAD

**Issue by apetrynet** [PixarAnimationStudios/OpenTimelineIO#267]
Hi!

Just want to inform people that I've been working on an MLT (Media Lovin' Toolkit) XML adapter so we don't overlap. 
MLT is the backbone of Kdenlive, Shotcut, melt (its own command line NLE) and a whole lot of other applications. My main focus will be to support the basic elements that are supported by melt and perhaps expand to the support some other applications further down the road.

At the moment I have basic writing of the mlt format in place. 
More info on MLT [here](https://www.mltframework.org/)

**Comment by apetrynet** [comment]
Just struck me that these notifications (#266) probably should go in the google mail group or is it OK to post stuff like this here?

**Comment by jminor** [comment]
This is a fine place for discussion like this, the Google Group is mostly for announcements. You could phrase the ticket as a request or topic like "Integration with MLT, Shotcut, etc." so it still reads well after the ticket is done :)

Integration between OTIO and other applications is very welcome. We don't have a place for it in the source repo yet, but there is at least one other similar project in the works (a plugin for Premiere) by another contributor. Given that the structure of each one it probably different, we could make a folder for them. Let me talk to @ssteinbach about the right folder structure for this, but some sort of contrib/plugins folder would likely work well.

**Comment by apetrynet** [comment]
OK, cool!
I renamed the issue.
This MLT adapter is in fact an adapter and should go in contrib I guess. #266 is more like a plugin.
Stay tuned.. :)

**Comment by ssteinbach** [comment]
Cool.  There are patterns for setting environment variables when necessary and gracefully failing when requirements aren't present (see the RV adapter or maya adapter for example).  It would also be nice if you could include a unit test of some kind.  Thanks!

**Comment by apetrynet** [comment]
thanks!
The adapter is still quite rough, but I'll write a unit test for it once I have all the basics covered.

**Comment by apetrynet** [comment]
Tiny status update.
The adapter is still a bit messy, but otio->mlt seems to work now. That includes cuts, simple time warps, dissolves and fades. Please note that I need to figure out if transparent fades are supported in MLT so only fade to/from black for now.

One of the intended use case for this adapter is to enable playback/playout of a timeline through [melt](https://www.mltframework.org/docs/melt/) (MLT's command line player)

TODO's includes, audio tracks, mlt->otio and unit tests.

For those who would like to check it out you can find it in under the `opentimelineio_contrib/adapters` in my "mlt_xml_adapter" [branch](https://github.com/apetrynet/OpenTimelineIO/tree/mlt_xml_adapter)
Feel free to come with feedback in my repo.

**Comment by ssteinbach** [comment]
@apetrynet same note as on the other issue - feel free to open an `[WIP]` PR.  I had another thought - on the EDL adapter we have a 'style' argument.  I can think of at least one other XML flavor (Resolve) so adding an "MLT" flavor to the EDL adapter makes sense to me, and follows a pattern we already have in the library.  For details, see: 
https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/33ad026c7d46f106eb079f77324ffae6060691d5/opentimelineio/adapters/cmx_3600.py#L724

**Comment by apetrynet** [comment]
@ssteinbach The mlt_xml files have `.mlt` extension and shouldn't conflict with other adapters. 
That said, if I or anyone else should add support for other application's flavors of the mlt_xml, the adapter should perhaps have the `style` argument. I'll add it for future proofing and consistency. Thanks for the tip.

When it comes to creating a PR I'm in the middle of some tinkering on the adapter so It's probably best to finish that first before submitting.

**Comment by apetrynet** [comment]
Hi!

I've been working on a refactor of the mlt adapter the last couple of days and decided to drop mlt -> otio parsing. 
There are a couple of reasons for this:
* To my knowledge there aren't that many applications exporting the bare bones mlt files.
* The MLT XML format is quite flexible and supports many different configurations, so it's hard to catch'em all in a good way only using etree
* There is a python-mlt you can build with MLT that let's you read and write mlt files, but I didn't want to add a third-party dependency. Perhaps it makes more sense to write an otio plugin for MLT that can export otio files directly(?)

I've also simplified the code a bit so there's no more "clever" melt subprocess trying to make decisions based on the media files etc. leaving all of that up to melt during playback/render of the mlt file.

Still need to do some more testing but should be able to send a PR soon.

And of course, if anyone totally objects to my decisions I can always go a different route and use the python-mlt library.
Let me know what you think.

**Comment by reinecke** [comment]
I think your decision to drop mlt->otio makes sense. I'd guess the 90% use case would be writing out compositions for MLT to render, this should cover that nicely. I think it is totally acceptable to have one-way adapters in these sorts of cases.

I look forward to seeing what you have!

**Comment by apetrynet** [comment]
Yeah, I think that's the case as well.  
Thanks @reinecke !

**Comment by apetrynet** [comment]
@reinecke @ssteinbach @jminor 
Is it good practice to raise a `NotImplementedError` if `read_from_string` is not implemented in an adapter or should I leave it up to  otio.adapters to raise an exception?

**Comment by jminor** [comment]
There's some code in `adapter.py` that attempts to handle the cases where `read_from_string` or `read_from_file` are missing. See the calls to `has_feature` in here: https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/master/src/py-opentimelineio/opentimelineio/adapters/adapter.py#L106

I think the pattern is for each adapter to only implement the functions it actually supports and leave the others missing so the generic adapter system can either fall back to the other one, or report the problem.

Similarly for read-only or write-only adapters. If you just implement the ones that actually work, the system should detect that.

**Comment by apetrynet** [comment]
Great! Thanks!

**Comment by apetrynet** [comment]
Closing ticket.
Adapter released as plugin available through [pypi](https://pypi.org/project/otio-mlt-adapter/)
