### ISSUE TITLE
Adapter warning/error reporting

### ISSUE THREAD

**Issue by jminor** [PixarAnimationStudios/OpenTimelineIO#28]
Adapters should be able to report warnings and errors to the caller in a clear way.

**Comment by jminor** [comment]
This would be handy for cases like the `ignore_timecode_mismatch` flag on the EDL adapter. You don't just want to ignore problems, nor do you want them printed to the console.

Ideally you could provide a callback or handler that can accept warning messages, or progress notifications, and choose to stop or continue on each one.

**Comment by jminor** [comment]
There are several places where we raise `ValueError` and `TypeError` exceptions, which should really be custom sublcasses of `OTIOError` so the caller can distinguish OTIO-related issues with just coding errors.

**Comment by meshula** [comment]
flagging for TSC review, is there work to do here, or has the concern been addressed?

**Comment by reinecke** [comment]
The exception-based error reporting mechanism paired with controls via adapter args to fudge certain data is the way we'd like to proceed with this.
