### ISSUE TITLE
Otioview should open with the contents scaled to the view

### ISSUE THREAD

**Issue by boredstiff** [PixarAnimationStudios/OpenTimelineIO#292]
The view should open with the items in the Timeline/tracks scaled to the view. Without this, the user has to immediately scroll in to see anything in the view every time the view opens.

What currently happens, upon opening:
![image](https://user-images.githubusercontent.com/3489076/43056033-a3d0c80c-8dee-11e8-8516-5920ca5f3b7b.png)

What I expect to see, upon opening:
![image](https://user-images.githubusercontent.com/3489076/43056050-beea681e-8dee-11e8-856a-83b82523b8ac.png)

I can handle doing this, I'm just recording the issue here to log it.

**Comment by jminor** [comment]
I wonder if this is also related to the fact that sometimes OTIOView shows the tracks with large empty areas at the end. That has bothered me in the past, but we haven't spent the time to track it down.

**Comment by ssteinbach** [comment]
Addressed by #378 and #449
