### ISSUE TITLE
EDL Adapter 'append' file 

### ISSUE THREAD

**Issue by col-one** [PixarAnimationStudios/OpenTimelineIO#303]
Hello ! 
Maybe I miss something, but it will be very useful to append edl file has new track. Ex: 

eld-01 : [---clip01---][---------clip02---------][-clip03-]
eld-02 : ...................[-clip02.1-][-clip02.2-].............

This is a common use case to manage splitscreen effect. 

pseudo code:
```python
timeline = otio.adapters.read_from_file(edl-1)
otio.adapters.append_from_file(edl-2, timeline=timeline)
```

Thanks a lot ! .

**Comment by jminor** [comment]
You can read multiple EDLs into a multi-track timeline like this:

```
# make an empty timeline
timeline = otio.schema.Timeline()
for path in paths:
  # read an edl
  edl = otio.adapters.read_from_file(path)
  # append all of the edl tracks onto our timeline
  timeline.tracks.extend(edl.tracks)
# write the result to disk
otio.adapters.write_to_file(timeline, "multitrack.otio")
```

The EDL adapter only supports a single video track, but may have multiple audio tracks. If you want just the video track, then `timeline.tracks.extend(edl.video_tracks())`

**Comment by col-one** [comment]
It's perfect ! Thank you so much.
