### ISSUE TITLE
OpenTimelineIO Documentation

### ISSUE THREAD

**Issue by sobotka** [PixarAnimationStudios/OpenTimelineIO#304]
Would it be feasible to have autobuilds of the documentation available for PDF downloading similar to what Larry Gritz does for OpenImageIO?

In addition to PDF for offline use,  would it be feasible to consider implementing live documentation via  ReadTheDocs? Colour Science has done an incredible job in this regard that covers tags etc. https://www.colour-science.org/api-reference/

**Comment by jminor** [comment]
Addressed by #312 

Documentation is now here: https://opentimelineio.readthedocs.io/en/latest/
with offline PDF here: 
https://readthedocs.org/projects/opentimelineio/downloads/pdf/latest/
