### ISSUE TITLE
Docs should be easier to find

### ISSUE THREAD

**Issue by jminor** [PixarAnimationStudios/OpenTimelineIO#308]
Some people are having trouble finding the wiki docs, especially the Timeline Structure page: 
https://github.com/PixarAnimationStudios/OpenTimelineIO/wiki/OTIO-Timeline-Structure

We should promote this on the main README with an image and a link.

**Comment by jminor** [comment]
That sounds great. Also, there are some API docs, but without much visibility they don't get much attention.

**Comment by boredstiff** [comment]
K. I did a rough branch with this this weekend, and hit an issue and decided to wait until I got a response before proceeding on it. I'll continue working on it and submit it something in the next few days, probably.
