### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by boredstiff** [PixarAnimationStudios/OpenTimelineIO#311]
![screen shot 2018-08-19 at 11 13 43 pm](https://user-images.githubusercontent.com/3489076/44323186-a54ed980-a405-11e8-8c65-28999d6c244f.png)

![screen shot 2018-08-19 at 11 15 15 pm](https://user-images.githubusercontent.com/3489076/44323221-cdd6d380-a405-11e8-9a0f-77f8ff33565d.png)

What do you all think about having a dark mode for otioview?

I could either have a dark mode be the default, or have it not be a default and be enabled through an Action in the File menu.

**Comment by jminor** [comment]
Looks nice to me. Is that via a style sheet?

**Comment by boredstiff** [comment]
Yeah, it's only a couple of lines, nothing complex at all. Would you want it to be default or capable of being enabled?

**Comment by jminor** [comment]
Default is fine with me. The complexity of making sure both work is probably not worth it.
