### ISSUE TITLE
If this is no existing shot in the maya scene, build_sequence() will raise error

### ISSUE THREAD

**Issue by NickWu** [PixarAnimationStudios/OpenTimelineIO#323]
When running extern_maya_sequencer.build_sequence() on an empty scene, the tool will error. This error is due to the initialization of en empty list when no shot nodes in a scene:

https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/f5a4480d7418cfbfea6b7604e9d28b46e4c683aa/opentimelineio_contrib/adapters/extern_maya_sequencer.py#L129

And the _build_track() function is using `if existing_shots is not None:` to test whether there are existing shots which will be `[] ` instead of `None` when no shots in a scene:

https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/f5a4480d7418cfbfea6b7604e9d28b46e4c683aa/opentimelineio_contrib/adapters/extern_maya_sequencer.py#L120

Then, the following `existing_shot = _match_existing_shot(item, existing_shots)` will error with the following message: 

```
#     url_path = _url_to_path(item.media_reference.target_url)
# AttributeError: 'GeneratorReference' object has no attribute 'target_url' # 

```

**Comment by heylenz** [comment]
Can you provide the file you read? I am testing edl file  and I will not report error.

**Comment by NickWu** [comment]
Hi @heylenz, sorry for replying late, as I have been in the middle of

**Comment by NickWu** [comment]
Thanks @heylenz . I closed it for now as I don't have a chance to test it further at the moment. By the way, I was using maya 2018 when coming across the issue. I am not sure whether that makes difference, but I will check that further once I get a chance.  Thank you for looking into it.
