### ISSUE TITLE
Typo Adapter section of the wiki

### ISSUE THREAD

**Issue by apetrynet** [PixarAnimationStudios/OpenTimelineIO#329]
Hi!
There seems to be a typo in the custom [adapters](https://github.com/PixarAnimationStudios/OpenTimelineIO/wiki/How-to-Write-an-OpenTimelineIO-Adapter#custom-adapters) section of the wiki regarding the plugin manifest environment variable.
I assume `OTIO_OTIO_PLUGIN_MANIFEST_PATH` is supposed to be `OTIO_PLUGIN_MANIFEST_PATH` ?
I did a grep for `OTIO_OTIO_PLUGIN_MANIFEST_PATH` and `OTIO_PLUGIN_MANIFEST_PATH` which confirms my suspicion.

**Comment by ssteinbach** [comment]
Yup. Good catch, fixed.
