### ISSUE TITLE
Enable macOS and Windows CI on GitHub Actions

### ISSUE THREAD

**Issue by jminor** [PixarAnimationStudios/OpenTimelineIO#333]
Travis supports macOS testing too. We should enable that to ensure that we don't have platform-specific bugs/problems.

Ideally we would have Windows too, but Travis doesn't support that (yet).

**Comment by jminor** [comment]
It looks like this should be very easy to turn on: https://docs.travis-ci.com/user/multi-os/

**Comment by jminor** [comment]
Whoa, that sounds like a mess. I had no idea it would be such a pain. Thanks for digging into this. Let’s leave it as-is for now. 

In the long run we can look for other CI services (which might happen for other reasons), or wait until Travis improves this.

**Comment by jminor** [comment]
Now that we've switched to GitHub Actions, maybe we can give this another try? It would be nice to know that everything works as expected on Mac, Windows, and Linux.

**Comment by KarthikRIyer** [comment]
If tox works without changes on Mac and windows then it should be easy.

**Comment by reinecke** [comment]
Given that we are looking to phase out tox, this may be a good opportunity to try building wheels using `cibuildwheel`: https://cibuildwheel.readthedocs.io/en/stable/setup/#github-actions

(see #666 also for more info about wheel building)

**Comment by ssteinbach** [comment]
closed by #873
