### ISSUE TITLE
otioconvert should support turning the media linker off via the --media-linker flag

### ISSUE THREAD

**Issue by avrata** [PixarAnimationStudios/OpenTimelineIO#354]
When testing with `otioconvert` in an environment that was bootstrapping and forcing a `OTIO_DEFAULT_MEDIA_LINKER` env value, I was unable to disable the media linker via the `--media-linker` flag. It would be nice if it supported something like `--media-linker ""`.

Thanks,
Robyn

**Comment by ssteinbach** [comment]
See #355
