### ISSUE TITLE
Final Cut Pro X XML Adapter

### ISSUE THREAD

**Issue by jminor** [PixarAnimationStudios/OpenTimelineIO#37]
After we complete the Final Cut Pro 7 XML Adapter (see https://github.com/PixarAnimationStudios/OpenTimelineIO/issues/2)
we will build support for the newer Final Cut Pro X XML format, which is slightly different.

Apple has offered advice/guidance on the differences between the 7 and X formats.

**Comment by latenitefilms** [comment]
@jminor - Hey Joshua! Curious... has any work already been started on this adapter?

**Comment by jminor** [comment]
We have support for the FCP 7 XML format, which works well for interoperation with Adobe Premiere, but I don't know of anyone working on the FCP X XML adapter. The two formats are similar, but there are enough differences that it probably makes sense to split it into two different adapters.

If you're interested in working on that adapter, we can put you in contact with someone at Apple who can answer questions about the format.

**Comment by jminor** [comment]
For reference, this is the documentation for the current Final Cut Pro X XML 1.8 https://developer.apple.com/library/content/documentation/FinalCutProX/Reference/FinalCutProXXMLFormat/Introduction/Introduction.html#//apple_ref/doc/uid/TP40011227-CH1-SW1

**Comment by ssteinbach** [comment]
Addressed by #309
