### ISSUE TITLE
Sometimes the AAF reader puts Clips in the top-level Stack

### ISSUE THREAD

**Issue by jminor** [PixarAnimationStudios/OpenTimelineIO#384]
We fixed this once before in #325, but didn't add a unit test, so then later, #366 re-introduced the problem. We need to make a sample AAF that covers this cleanly so we can ensure the simplify is doing what we want in both cases.

**Comment by alatdneg** [comment]
Yep I'm seeing this in my timeline.

**Comment by ssteinbach** [comment]
I think this might fix the issue, in case anyone else is seeing it.  It does change the simplifier, so you *might* get a different AAF out of it.

see: #435

**Comment by alatdneg** [comment]
Still getting clips that aren't children of tracks, or is that valid ?

I could probably email you the otio file once I've stripped out anything show based.

----- Original Message -----

**Comment by ssteinbach** [comment]
Can you send it with simplify=False also?  I want to see what the raw structure before simplification is.

**Comment by alatdneg** [comment]
Not simplified and simplified.

https://gist.github.com/alatdneg/9e06a2f3f716682fd5076ba59e2473c7
https://gist.github.com/alatdneg/c8318bee41ccde842771190048be35ac


----- Original Message -----

**Comment by ssteinbach** [comment]
Awesome, thanks. I’ll take a look.

**Comment by ssteinbach** [comment]
Addressed by #440
