### ISSUE TITLE
Support for speed up, slow down effects

### ISSUE THREAD

**Issue by jminor** [PixarAnimationStudios/OpenTimelineIO#39]
Most NLEs support effects which speed up or slow down clips. OTIO should support this also.

There are three important questions that applications using OTIO will want to know:

1. Does this Item have a speed vary effect on it?
2. For each frame of output, which frame of source should be displayed?
3. For a given clip, what is the earliest and latest source frame visible on the timeline?

Note that in the case of backwards playback or non-linear timing effects, the earliest source frame may not be the first one visible in the output (same for the latest source frame not being the last).

Many of the OTIO workflow use cases center on #3 (source media bounds) more so than #2 (per-frame source), which is more about playback or rendering. Also, #2 might deal with frame blending or other compositing features that are not central to OTIO. Even so, we will try to support both.

Lets start by researching how AAF, FCP, EDL and other formats handle speed effects.

**Comment by ssteinbach** [comment]
Addressed by #251 in the EDL adapter.
