### ISSUE TITLE
TimeRange sentinel values?

### ISSUE THREAD

**Issue by meshula** [PixarAnimationStudios/OpenTimelineIO#394]
> currently schemas can hold None for their time range

I'd like if there were sentinel values in TimeRange for None, Never and Always
With these rules embodied in union and intersection:
```
t U None = t
t U Never = t
t U Always = Always
t ^ None = t
t ^ Never = Never
t ^ Always = t
```
associativity, commutativity, and distribution appear to work correctly.

**Comment by ssteinbach** [comment]
This kind of relates to something @reinecke was poking at in #367.  I wonder if something like StartsAtOpen, EndsAtOpen would be useful?

**Comment by meshula** [comment]
it is related, carrying the conversation over there...!
