### ISSUE TITLE
AAF MediaReference start_time

### ISSUE THREAD

**Issue by alatdneg** [PixarAnimationStudios/OpenTimelineIO#409]
I'm trying to write an essence extractor that injects MediaReferences into an embedded aaf, I can extract the data etc. but the clip source start_times are not matching up, is there a way of determining the start_time for the media I've extracted ?

Currently all the media_references starts a frame 0, but the clip source ranges are all around  01:00:00:00.

As the essences are dnxhd streams, there's no timecode data, I guess it might be stored in  an associated mob, but I've no idea where to look.

Anyone know what I should be doing here ?

cheers!

**Comment by jminor** [comment]
I believe that we are looking at extracting the start timecode and duration for media references from an AAF since we will need that when writing AAF compositions (#236). @shahbazk8194 and @freesonluxo do you have any info that might be helpful to @alatdneg ?

**Comment by freesonluxo** [comment]
Hi @alatdneg. We are currently in progress and looking at the start timecode issue.

**Comment by jminor** [comment]
@alatdneg does #410 provide what you need?

**Comment by alatdneg** [comment]
If it does what I'm, after then yes ;) I'm currently using the StartTime metadata field, which I think gives the frame offset for the media, (though I might be mistaken)

**Comment by jminor** [comment]
Okay #410 has landed into master. @alatdneg can you give it a try?
When you read a clip from an AAF, you should now be able to ask for its `clip.media_reference.available_range.start_time` to get the start of the media independent from the clip's source_range (which is the trimmed segment used by the clip).

**Comment by ssteinbach** [comment]
@alatdneg did you guys get a chance to try this?  Wondering if we can close this issue.
