### ISSUE TITLE
SerializableCollection does not accept unicode strings on name attribute

### ISSUE THREAD

**Issue by felixsan** [PixarAnimationStudios/OpenTimelineIO#414]
I was building a collection of timelines and wanted to pass it all the respective names but hit a `TypeError` as the timeline names are coming out as unicode instead of strings.

The constraint appears to be set [here](https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/master/opentimelineio/schema/serializable_collection.py#L68).

**Comment by ssteinbach** [comment]
Addressed by #475
