### ISSUE TITLE
issue with opening AAF file

### ISSUE THREAD

**Issue by jamesmclaren** [PixarAnimationStudios/OpenTimelineIO#415]
I'm having problems with opening AAF files

getting the following exception

 File "D:\virtualenv\axiscuts\lib\site-packages\opentimelineio_contrib\adapters\advanced_authoring_format.py", line 415, in _transcribe
    result
opentimelineio.exceptions.OTIOError: Wrong duration? 98 and 98

this seems to be because it's comparing a long to a string. I've tracked down the issue to 

def _transcribe_property(prop) in advanced_authoring_format.py not handling longs in the list of exceptions at the start

ie the first line should read

    if type(prop) in (str, type(u""), int, long, float, bool):
        return prop

        not

    if type(prop) in (str, type(u""), int, float, bool):
        return prop

**Comment by ssteinbach** [comment]
Can you provide a simple example AAF which demonstrates the problem?  then we can add a unit test.  Thanks!

**Comment by ssteinbach** [comment]
I think this is addressed by #416

**Comment by jamesmclaren** [comment]
Hi Stephen,
That looks like it might work too.
Sorry I couldn't get you an example, don't have a license for Avid, and the files I could get hold of we're all company sensitive


---- Stephan Steinbach wrote ----


I think this is addressed by #416<https://github.com/PixarAnimationStudios/OpenTimelineIO/pull/416>

**Comment by ssteinbach** [comment]
@jamesmclaren we've landed #416 - if you get the chance, could you test to see if this addresses the bug you saw?  Thanks!

**Comment by ssteinbach** [comment]
@jamesmclaren closing this!  let us know if you hit any other issues!
