### ISSUE TITLE
Can't remove clip from stack

### ISSUE THREAD

**Issue by alatdneg** [PixarAnimationStudios/OpenTimelineIO#436]
When removing a clip from it's parent using it's index number I get a KeyError, the key seems to be the clip object itself, not the index I passed.

```
> del clip_parent[clip_idx]
> 
>   File "opentimelineio/core/composition.py", line 711, in __delitem__
>     self._child_lookup.remove(old)
> KeyError: otio.schema.Clip(name='b9000_LOP_DIR_AP_v004-DNE....
```

**Comment by alatdneg** [comment]
I think you _child_lookup is basically broke, if you add an item to it, any subsequent modification to the item will not be reflected. I think you're basically storing the baked string representation of the item at the point in time it's inserted.
```
>>> s = set()
>>> b = {"a":1}
>>> s.add(str(b))
>>> b["a"] = 2
>>> s.remove(str(b))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: "{'a': 2}"
>>> 

```

**Comment by alatdneg** [comment]
Ah your making you class hashable.. Hmm what is going on...         old = self._children[key]

```
        # remove it from the membership tracking set
        if old is not None:
            if isinstance(key, slice):
                for val in old:
                    self._child_lookup.remove(val)
            else:
                self._child_lookup.remove(old)
```
somehow hashing old isn't matching the entry in self._child_lookup

**Comment by alatdneg** [comment]
I'm removing a clip from a stack if that helps.

**Comment by ssteinbach** [comment]
I'm having trouble reproducing this, can you make a simple example of the bug?

This works, for example:

```python
    st = otio.schema.Stack("top_stack")
    cl = otio.schema.Clip("child_clip")

    st.append(cl)
    ind = st.index(cl)
    assert(ind == 0)

    cl.media_reference = otio.schema.ExternalReference("test")
    cl.source_range = otio.opentime.TimeRange(
        otio.opentime.RationalTime(10, 24)
    )

    del st[ind]

    assert(cl not in st)
```

Also, the `__hash__` function for everything other than the `opentime` classes should be the pointer, so modifying the clip after inserting it shouldn't change the `hash(cl)` value of the clip?  We made that change in #257 I think.  That said, if you insert the clip and then clone it, the new copy will have a new pointer and will not hash to the same thing as the old one.  Is that possibly what is happening?

**Comment by alatdneg** [comment]
Hmm not sure, I've no idea how it's doing this, would the cloning apply to replacing source_range etc...

----- Original Message -----

**Comment by ssteinbach** [comment]
No, by clone I mean:
```python
    st = otio.schema.Stack("top_stack")
    cl = otio.schema.Clip("child_clip")

    st.append(cl)
    ind = st.index(cl)

    cloned_cl = copy.deepcopy(cl)
    assert(cl.is_equivalent_to(cloned_cl))
    assert(hash(cl) != hash(cloned_cl))
    assert(id(cl) != id(cloned_cl))
    old_id = id(cl)
    old_hash = hash(cl)

    cl.media_reference = otio.schema.ExternalReference("test")
    cl.source_range = otio.opentime.TimeRange(
        otio.opentime.RationalTime(10, 24)
    )
    assert(not cl.is_equivalent_to(cloned_cl))
    assert(hash(cl) == old_hash)
    assert(id(cl) == old_id)
```

The deepcopy has returned a new object with a new pointer, so new hash.

**Comment by alatdneg** [comment]
Don't think I do, but either way, the del function in the container shouldn't be able to throw the way it does.

I put a hack in the code to check the returned object exists in the set, before it tries removing it. But how it's managing to get in that state I've no idea.

----- Original Message -----

**Comment by ssteinbach** [comment]
Ok!  I managed to trigger something that looks like this bug by assigning the stack with a slice, is that possibly what you are doing?

```python
st[:] = [cl]
```

I'll fix this bug, but I'm wondering if you have something like that in your code.

**Comment by ssteinbach** [comment]
I'll make a PR for this, good catch!

**Comment by ssteinbach** [comment]
@alatdneg can you try #437 and see if that addresses the issue?  I'm not sure if this is your exact case, but it produces the same trace back and was definitely a bug.

**Comment by alatdneg** [comment]
Pretty sure I don't do that, but I'll try the patch and see if it helps.

----- Original Message -----

**Comment by alatdneg** [comment]
Looks like that fixed the issue, I can now inject tracks into the bare clips in my aaf.

----- Original Message -----

**Comment by ssteinbach** [comment]
The aaf adapter was doing it!

**Comment by alatdneg** [comment]
yeah I suspected as much.

----- Original Message -----
