### ISSUE TITLE
AAF Writer: Improve implementation to not require clip metadata

### ISSUE THREAD

**Issue by freesonluxo** [PixarAnimationStudios/OpenTimelineIO#439]
Right now the AAF writer relies on SourceMobSlotID and SourceID and only supports existing clips in Avid. We would like to not rely on metadata for AAF writing

**Comment by freesonluxo** [comment]
@shahbazk8194

**Comment by freesonluxo** [comment]
A possible solution would be - for AAF files that compose AAF files, we could read in the clip MobIDs from the AAF files as a prepass. Basically, we would cheat and look at the AAF files if they are there.

**Comment by jminor** [comment]
Addressed by #460
