### ISSUE TITLE
AAF reader hard coded to 24fps?

### ISSUE THREAD

**Issue by andrewmoore-nz** [PixarAnimationStudios/OpenTimelineIO#464]
The AAF adapter appears to currently be hard coded to read everything at 24fps. 

Line 184 in `/opentimelineio_contrib/adapters/advanced_authoring_format.py`:

`def _transcribe(item, parent=None, editRate=24, masterMobs=None):`

When this function is called from within `read_from_file()` on lines 877 & 883, there is no editRate value passed in as an argument, so it defaults to 24. 

The AAF I am testing this on is from a 25fps project in Premiere, and I can see from reading the raw OTIO JSON string that this information is coming through in the metadata:

> "metadata": {
>     "AAF": {
>         "ClassName": "TimelineMobSlot", 
>         **"EditRate": "25",** 
>         "MediaKind": "Picture", 
>         "Name": "TimelineMobSlot", 
>         "Origin": 0, 
>         "PhysicalTrackNumber": 1, 

...

Is there a way that the correct frame rate can be deduced from the AAF metadata when parsing to create the OTIO model? We have currently hacked our own version of this to allowing for calling `read_from_file()` with a specified editRate value, but not really a solution to the problem.

**Comment by thecargocultnz** [comment]
I would add that if and when a default is needed for framerate, it should be some nonsense value like -1.

It's better that it completely blows up than return a seemingly complete sequence which is actually full of unseen issues.

**Comment by jminor** [comment]
I'll take a look.

**Comment by jminor** [comment]
Oops. Yeah, I can see that this is totally busted for non-24 fps AAFs. I see how to fix this.

**Comment by andrewmoore-nz** [comment]
Great... that'll be super handy if it can pull in the correct editRate from the AAF itself. 

On that note, I've been doing some testing today with AAFs coming out of DaVinci Resolve and they don't seem to be carrying the same metadata through in to the OTIO model i.e. there is no metadata object that comes with the track specifying the frame rate. Might there be somewhere else that this gets specified? Or any idea what might be happening there? Can provide one to look if it helps.

**Comment by jminor** [comment]
My fix #465 is almost ready.

For your other issue: Here is a simple idiom for finding the edit rate of a timeline: `edit_rate = timeline.duration().rate` Give that a try instead of peeking into AAF metadata and see if it works for you. If not, we can make some API to explicitly detect the edit rate.

**Comment by andrewmoore-nz** [comment]
Great... I can pull that fix down to test with as soon as it's available.

Thanks for the tip. Once I've been able to pull the fix I can test that out with the Resolve AAFs to see what happens... I can't get too far at the moment because all of the AAFs are still specified as 24fps.

Our work around for the hard coded 24fps argument was to look at the metadata block for the correct edit rate, and pass that back in as an argument on a second read attempt. Without having the required `TimelineMobSlot` or `EditRate` metadata info there, I wasn't too sure how to make this work.

**Comment by ssteinbach** [comment]
@andrewmoore-nz can you try it with #465 landed and see if that fixes your bug?  Thanks for reporting this!

**Comment by andrewmoore-nz** [comment]
@ssteinbach Just pulled that commit and all seems to be working fine. Our test AAFs are reading at the correct frame rate - from both Premiere and Resolve.

**Comment by jminor** [comment]
Yay!
