### ISSUE TITLE
null characters from Avid AAFs

### ISSUE THREAD

**Issue by thecargocultnz** [PixarAnimationStudios/OpenTimelineIO#474]
Avid Media Composer AAFs are causing JSON strings with null characters (\u0000). This makes it tricky to parse for anyone downstream.
Is there some way to sanitise these while parsing?

For the record: this example was caused by using the "Time Compression Expansion" Audiosuite effect.

[TCETest_MC1.aaf.zip](https://github.com/PixarAnimationStudios/OpenTimelineIO/files/3020346/TCETest_MC1.aaf.zip)

**Comment by jminor** [comment]
Specifically, if you read the provided AAF, you get this in the metadata:
` "AvidASPIPlugInName": "Time Compression Expansion\u0000\u0000\uf37e\u1029"`

**Comment by jminor** [comment]
This appears to be a bug in pyaaf2. @thecargocultnz would you like me to submit this bug to the upstream project?

**Comment by thecargocultnz** [comment]
@jminor for ourselves we found a way to sanitise the data - but I'd say this would be worth fixing as it'll catch out a lot of people. So not urgent for us, but definitely a bug.

**Comment by jminor** [comment]
I filed a pyaaf2 bug here: https://github.com/markreidvfx/pyaaf2/issues/49

**Comment by jminor** [comment]
This is fixed in pyaaf2 now: https://github.com/markreidvfx/pyaaf2/commit/37de8c10d3c3495cc00c705eb6c5048bc4a7e51f

Next time there's a release of pyaaf2 we can update our dependency, but in the meantime you can pull the latest master of pyaaf2 to get this fix.
