### ISSUE TITLE
AAF Writer: Provide media references to UNC Paths

### ISSUE THREAD

**Issue by JoshBurnell** [PixarAnimationStudios/OpenTimelineIO#551]
When using the AAF adapter to create an OTIO from an AAF, the resulting OTIO Clips contain MissingReference schemas that have a "UNC Path" path in the "UserComments."

```
"media_reference": {
    "OTIO_SCHEMA": "MissingReference.1",
    "metadata": {
    "AAF": {
        "MobID": "64d3faed",
        "Name": "2",
        "UserComments": {
            "Name": "1",
            "UNC Path": "\\tmp\\jburnell\\500_2349\\2.aaf"
        }
    }
}
```

It would be great if the AAF adapter created an ExternalReference instead that references the "UNC Path."

**Comment by jminor** [comment]
Addressed by #560 
Thanks @JoshBurnell !
