### ISSUE TITLE
setup.py should check if src/deps are empty

### ISSUE THREAD

**Issue by swallitsch** [PixarAnimationStudios/OpenTimelineIO#553]
src/deps are nested git repositories referencing specific commits for the required libraries. When missing, CMake gives a decent error but this could be improved with direct checking.

If 'git' is found in the path, setup.py could even attempt a git checkout during the build.

**Comment by ssteinbach** [comment]
good call.  there are already a bunch of checks in there, I can add one for this.

**Comment by ssteinbach** [comment]
I think it makes more sense to put that check in the cmake build system rather than setup.py -- let me know if this makes sense! #556

**Comment by swallitsch** [comment]
Yes absolutely. Sorry I was just going off what we briefly discussed at siggraph
