### ISSUE TITLE
Use `os.pathsep` instead of `:` for parsing `OTIO_PLUGIN_MANIFEST_PATH`

### ISSUE THREAD

**Issue by ssteinbach** [PixarAnimationStudios/OpenTimelineIO#581]
This line of code causes problems on windows:
https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/1ac88cbe6626b4220058c4a97e56f91026f2c5d8/src/py-opentimelineio/opentimelineio/plugins/manifest.py#L259

**Comment by JoshBurnell** [comment]
I'm not seeing this change in master. Did it get clobbered by c89b24d834b0dee21aa796d6fdafc5175239a66c ?

**Comment by JoshBurnell** [comment]
Crap, no. It got clobbered by mine: 44a0c44735799c74146bff3619bab0ce0cda82d6
