### ISSUE TITLE
media_linker.load_manifest clobbers local Adapters of similar suffix

### ISSUE THREAD

**Issue by JoshBurnell** [PixarAnimationStudios/OpenTimelineIO#590]
For testing (and customizability), it would be useful to supersede the Adapters in the OpenTimelineIO distribution with local adapters of the same suffix.

media_linker.load_manifest doesn't allow this, because it processes the Adapter manifests in this order:
1. opentimelineio/adapters/builtin_adapters.plugin_manifest.json
2. opentimelineio_contrib/adapters/contrib_adapters.plugin_manifest.json
3. $OTIO_PLUGIN_MANIFEST_PATH

It would allow more customizability to process $OTIO_PLUGIN_MANIFEST_PATH first.
1. $OTIO_PLUGIN_MANIFEST_PATH
2. opentimelineio/adapters/builtin_adapters.plugin_manifest.json
3. opentimelineio_contrib/adapters/contrib_adapters.plugin_manifest.json

**Comment by JoshBurnell** [comment]
Submitted #591 to resolve.

**Comment by ssteinbach** [comment]
Fixed by #591
