### ISSUE TITLE
to_timecode ignoring RationalTime's rate

### ISSUE THREAD

**Issue by splidje** [PixarAnimationStudios/OpenTimelineIO#606]
How to reproduce:

``import opentimelineio as otio``
``time1 = otio.opentime.RationalTime(24.0, 24.0)``
``time2 = otio.opentime.RationalTime(1.0, 1.0)``

time1 and time2 are equivalent, here's proof:
``time1 - time2``
gives:
``otio.opentime.RationalTime(value=0.0, rate=24.0)``

converting time1 to a 24fps timecode:
``otio.opentime.to_timecode(time1, 24.0)``
_correctly_ gives:
``'00:00:01:00'``

however, converting time2 to a 24fps timecode:
``otio.opentime.to_timecode(time2, 24.0)``
_erroneously_ gives:
``'00:00:00:01'``

in fact, it seems the RationalTime's rate is being completely ignored by to_timecode, as converting time1 to a 12fps timecode:
``otio.opentime.to_timecode(time1, 12.0)``
_erroneously_ gives:
``'00:00:02:00'``

**Comment by reinecke** [comment]
Hi @splidje, thanks for filing! This is definitely an issue. I've checked the pip version as well as the C++ version and they both show the bug.
I'm sure you figured it out already, but the workaround is to rescale the `RationalTime` to the frame rate before converting:
`otio.opentime.to_timecode(time2.rescaled_to(24))`
gives:
`'00:00:01:00'`
