### ISSUE TITLE
Heads up: Avid avb parser 

### ISSUE THREAD

**Issue by tin2tin** [PixarAnimationStudios/OpenTimelineIO#626]
Here's a project which allows for reading and writing of Avid avb files: https://github.com/markreidvfx/pyavb

Maybe you guys can see a potential in adding this format to OTIO?

**Comment by ssteinbach** [comment]
Interesting.  Would they become SerializableCollections?

**Comment by ssteinbach** [comment]
After some discussion, we think a better approach would be to use ALE exports rather than directly manipulating the proprietary data of the AVB. Happy to re-open for further discussion, but going to close this for now.  Regardless, thanks for the heads up!

**Comment by dlogneb** [comment]
The problem with modifying an ALE file is it often won't "merge" back into the Avid.  Frame-rate, sample-rate, format – all these things can cause issues with using ALE files to enter metadata.

I can manually enter any metadata for clips in an Avid bin, but there is no way to (for example) paste a column, or correlate data based on another cell's value.   To be able to automate entry of metadata (and import data from text files) would be really useful.  The ALE functionality is somewhat limited.
