### ISSUE TITLE
TypeError: write() argument must be str, not bytes

### ISSUE THREAD

**Issue by michalfapso** [PixarAnimationStudios/OpenTimelineIO#636]
I get the error with this code:
```
#/usr/bin/env python
import opentimelineio as otio
mytimeline = otio.adapters.read_from_file("FinalCutProXML.xml")
otio.adapters.write_to_file(mytimeline, "export.kdenlive")
```
Here is the full error log:
```
Traceback (most recent call last):
  File "./convert.py", line 9, in <module>
    otio.adapters.write_to_file(mytimeline, "/media/miso/data/foto/2016-08-24..27 Torquay 1/premiere/export_kdenlive.kdenlive")
  File "/home/miso/.local/lib/python3.7/site-packages/opentimelineio/adapters/__init__.py", line 194, in write_to_file
    **adapter_argument_map
  File "/home/miso/.local/lib/python3.7/site-packages/opentimelineio/adapters/adapter.py", line 184, in write_to_file
    fo.write(result)
TypeError: write() argument must be str, not bytes
```
And here is the input xml file: [FinalCutProXML.zip](https://github.com/PixarAnimationStudios/OpenTimelineIO/files/4014002/FinalCutProXML.zip)

I solved it by changing "/home/miso/.local/lib/python3.7/site-packages/opentimelineio/adapters/adapter.py", line 184
from:
```
fo.write(result)
```
to:
```
fo.write(result.decode('utf-8'))
```
I am not sure if that is the correct solution though.

**Comment by ssteinbach** [comment]
I think this is a bug in the kdenlive adapter, can @vpinon  take a look?

Thanks!

**Comment by vpinon** [comment]
Hello,
This is exactly the goal of the simple fix in PR PixarAnimationStudios/OpenTimelineIO#646
Just need someone to merge it... @jminor, @ssteinbach?
