### ISSUE TITLE
EDL cmx 9600 tries to add the same clip to multiple tracks

### ISSUE THREAD

**Issue by gplsteph** [PixarAnimationStudios/OpenTimelineIO#642]
Hello,
I tried to used OTIO with some sample EDLs we use to test our editorial tools and one them raised the following error during EDL parsing:
>ValueError: Composable named 'mad.men.714.hdtv-lol.mp4' is already in a composition named 'A1', remove from previous parent before adding to new one. Composable: Clip("mad.men.714.hdtv-lol.mp4", MissingReference(None, None, {}), TimeRange(RationalTime(0, 24.0), RationalTime(81982, 24.0)), {}), Composition: Track(A1, [otio.schema.Clip(name='mad.men.714.hdtv-lol.mp4', media_reference=otio.schema.MissingReference(name=None, available_range=None, metadata={}), source_range=otio.opentime.TimeRange(start_time=otio.opentime.RationalTime(value=0, rate=24.0), duration=otio.opentime.RationalTime(value=81982, rate=24.0)), metadata={})], TimeRange(RationalTime(0, 24.0), RationalTime(81982, 24.0)), {})

Caused by an edit event like:
>003  AX       AA    C        00:00:00:00 00:56:55:22 00:00:00:00 00:56:55:22
>* FROM CLIP NAME: mad.men.714.hdtv-lol.mp4

It seems that the adapter tries to add the same clip to `A1` and `A2` tracks, following rules defined here: https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/master/src/py-opentimelineio/opentimelineio/adapters/cmx_3600.py#L77, but this is not allowed.

EDLs being some kind of wild west, may be the adapter should have a _permissive_ mode where only critical problems would cause errors, and others would just issue warnings ? Some extension of the `ignore_timecode_mismatch` mode? I had some problems with some ill formed `asc_sop` values, which in some cases could be ignored?
Thanks.

**Comment by apetrynet** [comment]
Without having tried a fix, could it be that one of these lines are redundant? https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/master/src/py-opentimelineio/opentimelineio/adapters/cmx_3600.py#L255-256

**Comment by reinecke** [comment]
Hi @gplsteph thanks for letting us know. I just submit PR #644 to fix this.

Do you happen to have an example of some of the `asc_sop` issues?

As we characterize recoverable issue in EDLs, I think starting to phase in some less strict parsing behavior may make sense. I think some of the cases are still a little unclear to us so we want to keep catching them to make sure we keep improving the adapter and don't risk pushing bad data into productions.

If you have other specific cases where lest strict parsing behavior would be helpful, I'd love to take a look and see what we can do.

**Comment by gplsteph** [comment]
Hello, thanks!
The `asc_sop` issue was caused by a bad string being set as the value. Not a real production example, just something we had in our tests suite to check we were able to retrieve this from EDLs. Our tools don't parse it, we just keep track of the string. Parsing it and using it is left to tools which really need it.
Given that this is retrieved from a comment which could (and will) be anything, that this is not stricly needed for a cut, I think that should be considered as a "bonus" and shouldn't cause parsing to fail. It might be a good idea as well to keep all comments in the clip meta data, even if they were parsed and produced something.
cheers.

**Comment by jminor** [comment]
@reinecke your PR looks good. @gplsteph can you verify that #644 addresses the audio track problem you found?

**Comment by gplsteph** [comment]
I looked at the code, and it seems it will. However I’m not sure if the writer will do the right thing. I think it will write two A tracks ?

**Comment by reinecke** [comment]
In a quick test I see it writing out a single `A` track, however this is using a somewhat contrived edl I created from your example above.

Would you be able to check against a more real-world case? I unfortunately haven't encountered this issue in the flavor of EDLs I've been working with. Would you be able to give us some more context on how these EDLs are used in your workflow and where the OTIO adapters fall short in supporting that? Also if you have any example EDLs you could share it would help us in improving our test suite.

**Comment by gplsteph** [comment]
Hello,
here are the EDL files we use for our own EDL parser unit tests. Some of them are real production EDLs, some others are examples we put together. 

Please note that some of these files have binary data at the end. I never knew from where this data came from, but, in doubt we have this in the code which loops over the EDL lines:
```
                    # Not sure why we have to do that ...
                    # Some crappy Windows thing ?
                    line = line.replace("\x1a", "").strip(" \n")
                    if not line:
                        continue
```

So, not sure if all these examples are real valid cases, we wrote our parser a couple of years ago, and added samples over the years.
Hope it helps.
[multiple_tests.zip](https://github.com/PixarAnimationStudios/OpenTimelineIO/files/4164639/multiple_tests.zip)

**Comment by reinecke** [comment]
@gplsteph Thanks for sharing these, this is a great test set.

The `0x1A` thing comes from the SMPTE specification 258M (descendent of the CMX3600 EDL spec published in the 80s). In part 5.1, it states:

> The end of an edit decision list is indicated by either:
>– the end of the storage medium;
>– a CONTROL-Z (SUB) character.

So technically those files adhere closer to the SMPTE spec, but realistically I think most people have abandoned that. There are some others I've seen with similarly weird characters at the beginning, but I still haven't figured those out.

Would you mind if we added some of your example files to the OpenTimelineIO repo so we can include them in our unittesting?

**Comment by gplsteph** [comment]
hello, no problem to add our files to the otio test suite. And thanks for the `0x1A` explanation!
