### ISSUE TITLE
Update Copyright notices on xges adapter

### ISSUE THREAD

**Issue by jminor** [PixarAnimationStudios/OpenTimelineIO#657]
Hi @thiblahute and @hwilkes-igalia, could you update the Copyright notice on `xges.py` and `tests_xges_adapter.py` to "Copyright Contributors to the OpenTimelineIO project" instead of "Igalia S.L"?

As part of our transition into ASWF, we are updating the Copyright notices in the project. We intend to switch all of the copyright notices from the various individual or company contributors to the broader phrasing "Copyright Contributors to the OpenTimelineIO project".

This does not change the actual copyright ownership at all. Each contributor still retains the copyright to their own contributions.

This change makes it easier to see that most of the project contains contributions from many people, and makes it clear that this is a community project.

You can see that we did this already for the Pixar copyright notices here:
#632

The notices are here:
https://github.com/PixarAnimationStudios/OpenTimelineIO/search?q=igalia&unscoped_q=igalia

**Comment by thiblahute** [comment]
Should not be a problem, just wondering who is considered "Contributors to the OpenTimelineIO project" and how are we supposed to get that list?

**Comment by jminor** [comment]
We have this: https://github.com/PixarAnimationStudios/OpenTimelineIO/graphs/contributors
but we'd like to introduce a `CONTRIBUTORS.md` file (or something similar) as well. Do you know of a good template/format for a contributors list?

**Comment by thiblahute** [comment]
Makes sense, thanks for the info.

I do not have a good template/format, in the project I am used to contributing we have the notice in each file as we used to have here.
