### ISSUE TITLE
Update Copyright/License on ffmpeg_burnins.py

### ISSUE THREAD

**Issue by jminor** [PixarAnimationStudios/OpenTimelineIO#658]
The file `ffmpeg_burnins.py` has an MIT license which differs from the rest of the OTIO source code. It should either be moved into a separate folder to clarify that it is an embedded dependency, so it should be re-licensed to conform with the rest of the project. (See also #632)

https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/master/contrib/opentimelineio_contrib/adapters/ffmpeg_burnins.py

**Comment by repsac** [comment]
Should be done now

**Comment by jminor** [comment]
Thanks @repsac !
Addressed by #679
