### ISSUE TITLE
Support the predicates from Allen's Interval Algebra for `TimeRange`

### ISSUE THREAD

**Issue by reinecke** [PixarAnimationStudios/OpenTimelineIO#659]
In https://cse.unl.edu/~choueiry/Documents/Allen-CACM1983.pdf
wikipedia summary: https://en.wikipedia.org/wiki/Allen%27s_interval_algebra

Allen defines a set of logical predicates for time ranges that we should implement in OTIO:

- [ ] before 
- [ ] meets
- [x] overlaps
- [ ] begins
- [x] during/contains
- [ ] finishes
- [x] equals

Note that in our case we have to consider the end point clusivity of the `TimeRanges`.

**Comment by ssteinbach** [comment]
The exhaustive set we'd like to support is this: https://en.wikipedia.org/wiki/Allen%27s_interval_algebra

**Comment by ssteinbach** [comment]
I believe that `overlaps` and `equals` are already implemented, is that correct?

**Comment by reinecke** [comment]
Looks like Overlaps is here (I use this a lot): https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/33e6e5de338ec1fa6cad65ae1819f95c002ee6f7/src/opentime/timeRange.h#L77-L83

Equal/not equal is here: https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/33e6e5de338ec1fa6cad65ae1819f95c002ee6f7/src/opentime/timeRange.h#L85-L91

And, correct me if I'm wrong, but the functionality of `during` might be modeled by `contains` (but inverse operator order)?: https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/33e6e5de338ec1fa6cad65ae1819f95c002ee6f7/src/opentime/timeRange.h#L69-L75

**Comment by ssteinbach** [comment]
I think you're correct about during/contains

**Comment by devansh289** [comment]
@reinecke I'd like to take on this!

**Comment by reinecke** [comment]
@devansh289 Excited to see what you come up with!

**Comment by KarthikRIyer** [comment]
@reinecke isn't this a GSoC project? I plan to include this in my proposal.
