### ISSUE TITLE
EDLParse Error for ASC_Out / ASC_Inp

### ISSUE THREAD

**Issue by maxnbk** [PixarAnimationStudios/OpenTimelineIO#678]
Apparently this is a thing?
Encountered an EDL with "* ASC_Out <lut_name>" / "* ASC_Inp <lut_name", probably from digitalvision/nucoda?

Do a ctrl-F for a reference in this file.
http://www.digitalvision.tv/w/images/1/18/EDL-Layer_Matte_and_Stereo_extensions.pdf

I'll edit this with an EDL sample in question in a moment..

```
TITLE:   SCRAMBLE_NAME
FCM: NON-DROP FRAME
00001  SCRAMBLE-1D     V     C        18:24:20:01 18:24:21:19 01:00:00:00 01:00:01:18
* ASC_SOP (1.0000 1.0000 1.0000)(0.0000 0.0000 0.0000)(1.0399 1.0399 1.0399)
* ASC_SAT 1
* ASC_Out LUT_NAME
00002  SCRAMBLE-2D     V     C        00:46:17:04 00:46:17:22 01:00:01:18 01:00:02:02
* ASC_SOP (1.0000 1.0000 1.0000)(-0.0745 -0.0745 -0.0745)(0.9412 0.9412 0.9412)
* ASC_SAT 1
* ASC_Out LUT_NAME
00003  SCRAMBLE-3D  V     C        00:46:17:22 00:46:20:04 01:00:02:02 01:00:04:08
* ASC_SOP (1.0000 1.0000 1.0000)(-0.0745 -0.0745 -0.0745)(0.9412 0.9412 0.9412)
* ASC_SAT 1
* ASC_Out LUT_NAME
```

**Comment by reinecke** [comment]
Hi @maxnbk, are the `ASC_Out` and `ASC_Inp` comments specific to DigitalVision products or do they come from a more commonly-defined convention/specification like `ASC_SAT` and `ASC_SOP`?

I see that you should still be able to get at the data in the clip's metadata dictionary under the CMX3600 comments:
```json
"cmx_3600": {
    "comments": [
        "ASC_Out LUT_NAME"
    ]
}
```

In general, we wouldn't add parsing for specific EDL comments unless they're a broadly adopted convention or standard.

**Comment by ssteinbach** [comment]
@maxnbk going to close this for now - feel free to respond if you have further questions!  Thanks!
