### ISSUE TITLE
Sequence/Stack <format> stripped in fcp_xml adapter

### ISSUE THREAD

**Issue by faulknermano** [PixarAnimationStudios/OpenTimelineIO#680]
This is both a bug report and a question at the same time.

As a bug report: In an fcp-xml coming out of Premiere under the nested tags <sequences -> media -> video> there is a <format> tag. This does not get included  (ignored) in the otio object when the xml is read in. The tag in question is the first <format> and underneath that.

```xml
<?xml version="1.0" ?>
<xmeml version="4">
    <project>
        <name>editorial__v002.xml</name>
        <children>
            <sequence id="sequence-1">
                <name>editorial__v002.xml</name>
                <duration>344</duration>
                <rate>
                    <timebase>24</timebase>
                    <ntsc>TRUE</ntsc>
                </rate>
                <media>
                    <video>
                        <format>
                            <samplecharacteristics>
                                <rate>
                                    <timebase>24</timebase>
                                    <ntsc>TRUE</ntsc>
                                </rate>
                                <codec>
                                    <name>Apple ProRes 422</name>
                                    <appspecificdata>
                                        <appname>Final Cut Pro</appname>
                                        <appmanufacturer>Apple Inc.</appmanufacturer>
                                        <appversion>7.0</appversion>
                                        <data>
...
                                        </data>
                                    </appspecificdata>
                                </codec>
                                <width>1920</width>
                                <height>1080</height>
                                <anamorphic>FALSE</anamorphic>
                                <pixelaspectratio>square</pixelaspectratio>
                                <fielddominance>none</fielddominance>
                                <colordepth>24</colordepth>
                            </samplecharacteristics>
                        </format>
...
```

So as a question: is there a non-intrusive/modular way to magically include blocks of xml data (e.g. serialized fields??), or is this a matter of tweaking the adapter itself?

(Pardon if my questions are basic: I'm still trying to get grips on how OTIO works)

Thank you!

**Comment by faulknermano** [comment]
This is a sample [xml](https://github.com/PixarAnimationStudios/OpenTimelineIO/files/4427440/test_fcp_xml.zip) (which is effectively the same as the other one I attached in another [ticket](https://github.com/PixarAnimationStudios/OpenTimelineIO/issues/673))

**Comment by reinecke** [comment]
@faulknermano the FCP XML adapter should be taking any tags it doesn't explicitly parse and putting them in the metadata for their associate OpenTimelineIO object, see this conversion function: https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/d63e2497e7b82df04e4405477a7e72eb6b98614c/src/py-opentimelineio/opentimelineio/adapters/fcp_xml.py#L335)

Here is an example in use: https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/d63e2497e7b82df04e4405477a7e72eb6b98614c/src/py-opentimelineio/opentimelineio/adapters/fcp_xml.py#L857

On and off there have been incorrect values included in the `ignore_tags` that is passed to that at various levels. It's possible a metadata tree that should be included is getting ignored somewhere. This would be a bug in the adapter code.

As mentioned in #673, the provided XML file is invalid. Would you mind providing an updated version along with an example of what you'd expect to come through in the otio metadata?

**Comment by faulknermano** [comment]
@reinecke after a fresh look at this, I re-tested my xml by reading then immediately writing back and the data is indeed intact/present. So my previous dev results were erroneous to begin with. I'll close this issue as it seems to be pilot error on my part. Thank you!
