### ISSUE TITLE
C language bindings

### ISSUE THREAD

**Issue by jminor** [PixarAnimationStudios/OpenTimelineIO#693]
We would like to have a C wrapper API around the C++ implementation, which allows for easier integration with C-based applications, or as an intermediate layer for other language bindings where C is better suited than C++ (e.g. Lua, etc.)

**Comment by jminor** [comment]
Here are some examples of C wrapper APIs around C++ implementations:
https://github.com/bulletphysics/bullet3/blob/master/examples/SharedMemory/PhysicsClientC_API.h
https://developer.blender.org/diffusion/B/browse/master/intern/opencolorio/

If anyone knows of other examples that could be helpful here, please feel free to suggest them. There are several important choices in terms of memory management, linking, etc. that we should consider carefully.

**Comment by jminor** [comment]
@meshula, @ssteinbach and @KarthikRIyer do any of you have other examples of C wrapped C++ APIs that we can use as reference?

**Comment by KarthikRIyer** [comment]
I don't know about any good standard examples. The links you posted seem to be a good reference.
Here's a very simple C-CPP wrapper I made for my Swift data viz lib https://github.com/KarthikRIyer/swiftplot/tree/master/Sources/AGGRenderer/CAGGRenderer

Also, do we have tests for the CPP core (I don't think we do)? I was thinking of using [googletest](https://github.com/google/googletest) to set up tests for the C bindings. It's based on the xUnit architecture so it'll be similar to the JUnit tests I'll be using for Java bindings. And it's pretty compact.
Any thoughts?

**Comment by meshula** [comment]
cimgui https://github.com/cimgui/cimgui is a particularly interesting one. They use LuaJit and clang to scrape the Dear Imgui C++ headers to automatically generate the C binding.

**Comment by KarthikRIyer** [comment]
This looks interesting. 
I'm looking at this: http://samanbarghi.com/blog/2016/12/06/generate-c-interface-from-c-source-code-using-clang-libtooling/

I'll try to see if this works.
So currently building llvm-clang. The apt-get install of llvm and clang don't seem to provide the libtooling stuff.

**Comment by KarthikRIyer** [comment]
@meshula could you please note here and elaborate a little on the sample you mentioned in the TSC meeting to demonstrate the bindings?

**Comment by jminor** [comment]
Done! Thanks @KarthikRIyer :)
