### ISSUE TITLE
TimeRange contains and overlap do not match definitions

### ISSUE THREAD

**Issue by meshula** [PixarAnimationStudios/OpenTimelineIO#700]
The current implementations of contains and overlaps are sensible, but they don't match the requirements of Allen's Interval Algebra. They should be modified to match the specification as noted on this PR: https://github.com/PixarAnimationStudios/OpenTimelineIO/pull/697

**Comment by ssteinbach** [comment]
Fixed by PR: #760

**Comment by jminor** [comment]
Done!
