### ISSUE TITLE
Kdenlive adapter: write_keyframes function needs attention

### ISSUE THREAD

**Issue by reinecke** [PixarAnimationStudios/OpenTimelineIO#703]
The `write_keyframes` function started failing builds due to a lint issue (see #702). The expression `str(int(t.value))).format(v)` seems like it's unlikely to be correct. An integer converted to a string would never be a useful format template so it's unclear what the code is attempting to do.
Additionally the outer format on for the string `"{}={}"` is being passed a single value (a generator) rather than two values.

Code below:
```
def write_keyframes(kfdict):
    """Build a MLT keyframe string"""
    return ';'.join('{}={}'.format(str(int(t.value))).format(v)  # noqa: F524
                    for t, v in kfdict.items())
```

**Comment by reinecke** [comment]
@vpinon Would you mind taking a look at this one? I'm sure it's an easy fix, I'm just a little unfamiliar with the formats involved so I don't want to guess at how to correctly fix.

**Comment by vpinon** [comment]
@reinecke anything needed for merging my fix?
Thanks & Best Regards

**Comment by reinecke** [comment]
Merged your fix @vpinon. Thanks!
