### ISSUE TITLE
Doxygen documentation for the C++ code

### ISSUE THREAD

**Issue by ssteinbach** [PixarAnimationStudios/OpenTimelineIO#708]
It is an industry to convention to use Doxygen to generate documentation from C++ code, similar to how we use sphinx to generate the python docs.

- [ ] Add a make target that triggers a doxygen build of the code
- [ ] Integrate doxygen documentation with the readthedocs system
   - [ ] does doxygen have a similar theme to what readthedocs uses?
- [ ] Port comments in the C++ codebase to use doxygen conventions, bring comments back from older python version as necessary, and wrap through pybind11.
- [ ] Add documentation for how to trigger doxygen to the readthedocs documentation pages.

**Comment by hisergiorojas** [comment]
@jminor I want to work on this issue.
