### ISSUE TITLE
Add a style guide

### ISSUE THREAD

**Issue by ssteinbach** [PixarAnimationStudios/OpenTimelineIO#709]
Should cover:

- Python & C++ style
  - Python: PEP8
  - C++: a description of what goes into the clang-format file
- How the linters and formatters work for those two languages (pointers to the clang-format file for example)
- Be included in the readthedocs documentation

**Comment by meshula** [comment]
This commit, on the style-guide branch, https://github.com/PixarAnimationStudios/OpenTimelineIO/commit/418faedb744f9dcc0b95c30a4dc80382e71f8b01 contains a placeholder style guide where we can iterate.

**Comment by meshula** [comment]
committed draft
