### ISSUE TITLE
Adapters or place for "in context"use of otio

### ISSUE THREAD

**Issue by ssteinbach** [PixarAnimationStudios/OpenTimelineIO#76]
The way adapters currently work right now is for offline use, where it produces a file on disk (or a string in memory).  For cases where you want the adapter to produce a series of side effects (for example, if you're in an editing program and you want to load an OTIO file from disk into the state of the editing program) we don't currently have a place in the code base.  `read_into_context` has been suggested as an entry point, but I could also see those being in a separate "Scripts" directory that aren't loaded through the normal otio tool chain.  What does the community think?

**Comment by sobotka** [comment]
Is there a formal OTIO path that divides media into offline and online paths?

**Comment by jminor** [comment]
OTIO doesn't currently specify what the target_url of a media reference should be. Some of the adapters assume that it is a local path, but that isn't documented anywhere.

The assumption is that you (the developer) will provide a media_linker plugin that translates paths to match your needs - or you can write a simple re-link script that swaps the paths as needed.

What is your use case?
