### ISSUE TITLE
Add support for python 3.8

### ISSUE THREAD

**Issue by ssteinbach** [PixarAnimationStudios/OpenTimelineIO#786]
It seems as though it is time to add in python 3.8 support.  VFX Platform skips to 3.7 so we should be good to swap 3.6 for 3.8.

**Comment by apetrynet** [comment]
Other than a lot of versions to support, is there a reason not to keep python 3.6 support? 
I think centos7 stops at 3.6 without adding additional repositories or compiling.

**Comment by ssteinbach** [comment]
We're just dropping the entry from our CI -- trying to keep our support load closely tied to the VFX platform.

**Comment by apetrynet** [comment]
OK

**Comment by ssteinbach** [comment]
Closed by #787
