### ISSUE TITLE
PIX System Integration

### ISSUE THREAD

**Issue by ssteinbach** [PixarAnimationStudios/OpenTimelineIO#8]
## Would be nice to:
- Upload a `.otio` file and have it also upload associated media to pix
- Download a `.otio` file and get associated media from pix

**Comment by jminor** [comment]
Hey @rogergodspeed is this on your roadmap?

**Comment by rogergodspeed** [comment]
Not mine explicitly, but in Eric’s absence such tasks are likely to come my way.
