### ISSUE TITLE
Improve Github review process

### ISSUE THREAD

**Issue by jhodges10** [PixarAnimationStudios/OpenTimelineIO#809]
## Feature Request

- [x] Improve Github PR review process

## Description
We should introduce a `CODEOWNERS` [(info)](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners) file for starters which tags a group/team of reviewers.
Along with this, we could also look into some more advanced features that Github has like round-robin assignment - [info](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/managing-code-review-assignment-for-your-team).

## Context
Some recent PR's haven't gotten attention because nobody was tagged to review them automatically.

**Comment by meshula** [comment]
flagging for TSC review and to take a decision.

**Comment by reinecke** [comment]
We think that once we break the contrib adapters out this concept becomes less important - the OTIO core is more collaboratively maintained than specific adapters are.
