### ISSUE TITLE
Technical Steering Committee (TSC) Charter

### ISSUE THREAD

**Issue by jminor** [PixarAnimationStudios/OpenTimelineIO#815]
As part of the Academy Software Foundation graduation process, OpenTimelineIO needs to adopt a charter for our technical steering committee, which includes a governance model.

Here is the ASWF TSC charter template as a starting point:
https://github.com/AcademySoftwareFoundation/tac/blob/master/process/charter_template.md

**Comment by jmertic** [comment]
Here is a template of the charter with the relevant changes specific to this community included for the TSC to review...

https://github.com/AcademySoftwareFoundation/foundation/pull/5

**Comment by jminor** [comment]
Addressed by #1057
