### ISSUE TITLE
Split Swift bindings into otio-swift

### ISSUE THREAD

**Issue by meshula** [PixarAnimationStudios/OpenTimelineIO#835]
## Feature Request

Split Swift bindings into otio-swift

## Description

Create a new repo under ASWF for otio-swift and migrate the build there.

Modify the swift build so that it can find and bind to the correct OTIO dylibs. 

Unresolved, where should the OTIO dylibs be found?

Does otio-swift match our resolved naming convention?

**Comment by ssteinbach** [comment]
This is done here: https://github.com/OpenTimelineIO/OpenTimelineIO-Swift-Bindings
