### ISSUE TITLE
Adobe Premiere project adapter (.prproj)

### ISSUE THREAD

**Issue by splidje** [PixarAnimationStudios/OpenTimelineIO#840]
I'm creating this in order to mention I've begun working on an Adobe Premiere project adapter:

https://github.com/splidje/OpenTimelineIO/tree/adobe_premiere_project_adapter

**Comment by reinecke** [comment]
Hi @splidje, thank you for getting involved!

I'm curious what guide you have for parsing the project file format, is there something akin to the specification [Apple publishes for the FCP file format](https://developer.apple.com/library/archive/documentation/FinalCutProX/Reference/FinalCutProXXMLFormat/Introduction/Introduction.html#:~:text=With%20the%20Final%20Cut%20Pro,Final%20Cut%20Pro%20X%2010.4.)?

In the last conversations I had with Adobe, they actually urged us against directly parsing `prproj` files and instead suggested we use FCP XML for EDL interchange. Do yo know if their stance has changed on this?

Also, another option for adding a premiere adapter might be to publish it on your github as it's own adapter plugin package, there is an example of how to format one of these packages [here](https://github.com/PixarAnimationStudios/OpenTimelineIO/tree/master/examples/sample_plugin), also there is a real-world example [here](https://github.com/reinecke/otio-cookelensmetadata). I have yet to push to PyPi yet, but if you `pip install .` in your virtualenv with that repo, it adds support for that file format as if it were any other OTIO adapter.

Maintaining the adapter in its own repo and publishing it to [PyPi](https://pypi.org/) allows you to develop and release on your own pace without the OTIO core team having to code review and approve the work. It also allows you, if you choose, to take advantage of other pip libraries that we avoid using in the core to keep the base install footprint as small as possible.

**Comment by splidje** [comment]
Hi @reinecke, thanks for your reply.

I've so far just been reverse engineering the format. The use case would be situations where you want to automate something based on an edit made in Premiere, but have no access to Premiere - perhaps a machine without a UI.

I'll go the route you've mentioned above and create an adapter plugin package.

**Comment by splidje** [comment]
Is there some kind of naming convention? Does otio-premiereproject work as a name?

**Comment by splidje** [comment]
OK, here 'tis:
https://github.com/splidje/otio-premiereproject

**Comment by reinecke** [comment]
@splidje That's great! Please keep us updated on your progress. We'll be sure to send interested parties your direction when they ask about `.prproj` support!

Please feel free to contact us either on our [mailing list](https://lists.aswf.io/g/otio-discussion) or on the [slack channel](https://academysoftwarefdn.slack.com/archives/C019PV5UKGW) (you'll need to join the [ASWF Slack](https://slack.aswf.io/) first) if you have any questions or to get more involved with OTIO in general.

**Comment by reinecke** [comment]
@splidje Please feel free to tell me if you're not looking for feedback at this time, but I was taking a quick look at your adapter code and noticed you have `254016000000` hard coded in a lot of places. For those reading your code that are unfamiliar with Premiere's internal model (and so you don't have to copy/paste the number as much), it might be useful to create a constant at the top of the file like `PRPRO_TICKS_PER_SEC = 254016000000` - that lets readers of the code know why that number is special.

Also, an option I'd like, would be to have the adapter not convert from ticks into frames. I certainly see that there are probably a lot of workflows where converting back to frame numbers would be useful, but it's also nice sometimes to have the OTIO representation contain data as close to the source format's as possible. The [EDL adapter](https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/master/src/py-opentimelineio/opentimelineio/adapters/cmx_3600.py#L826) has a good example of how to expose arguments from your adapter if you're interested in allowing the user to choose.

**Comment by splidje** [comment]
Hello! I always welcome feedback, thanks for taking a look.

Totally agree about the hard-coded value. I think I was in my brute-force mode attempting to see if I could make sense of the format.

I've added the constant and created functions for the conversion. Also, it's adding the raw values to the metadata now too.

All in this commit:
https://github.com/splidje/otio-premiereproject/commit/18dbf8788b3b77610006605e0888b952ae3c0dc0
