### ISSUE TITLE
OTIO Version numbers as integers

### ISSUE THREAD

**Issue by vvzen** [PixarAnimationStudios/OpenTimelineIO#844]
## Feature Request

OTIO major, minor, bugfix version numbers exposed as integers on the `otio` module

## Description

Hi!
I'm writing some functionality to "translate" a Hiero sequence into a OpenTimelineIO Timeline, based also on this PR:  https://github.com/PixarAnimationStudios/OpenTimelineIO/pull/284 (which I was thinking of contributing to at some point)

Currently in our studio we're on `0.12.1`, which lacks the `ImageSequenceReference.1` class.
To make our code as much backward compatible as possible, I'm branching off based on the `otio.__version__` (which is  string, so in our case is`"0.12.0"`).

Right now I'm just splitting the string in 3 to get the major, minor, bugfix version, but I was wondering if you guys were thinking of having separate constants for that, since it's common practice and it would make the code look a bit cleanier since we wouldn't need to have our own "split the string" one line in difference places.

## Context

Instead of this:
```
OTIO_MAJOR_VERSION, OTIO_MINOR_VERSION, OTIO_BUGFIX_VERSION =  [int(v) for v in otio.__version__.split(".")]
if OTIO_MINOR_VERSION > 13:
    # use ImageSequenceReference.1
else:
    # use ExternalReference.1
```

it would be

```
if otio.MINOR_VERSION > 13:
    # use ImageSequenceReference.1
else:
    # use ExternalReference.1
```

This is a very minor request, but I was just wondering if there was a specific reason why you went with the string approach.
I don't know how you're generating this metadata, but I'd be happy to put together a quick PR in case I can help with that.

Thanks!

Valerio

**Comment by meshula** [comment]
> I don't know how you're generating this metadata

If you'd like to experiment, the version info is baked by setup.py. Look for METADATA_TEMPLATE, and you'll see how it works.

**Comment by vvzen** [comment]
Closing as per discussion on the Slack channel. The official way to do that is described here in the wiki: https://wiki.aswf.io/display/HOME/Python+Package+Versioning
