### ISSUE TITLE
OpenTimelineio should support Swift Package Manager (SPM)

### ISSUE THREAD

**Issue by davidbaraff** [PixarAnimationStudios/OpenTimelineIO#845]
## Feature Request

This is a new feature

## Description

We should be able to build the C++ libraries (and later the Swift bindings) via SPM.

**Comment by meshula** [comment]
Note, this means building the C++ libraries specifically, in this repo, as opposed to building the C++ libraries in the swift bindings repo, which already happens.

**Comment by davidbaraff** [comment]
FYI, there are some issues with the Readme.md and Examples subdirectories.
I have fixed them up here:

https://github.com/davidbaraff/OpenTimelineIO-Swift-Bindings.git <https://github.com/davidbaraff/OpenTimelineIO-Swift-Bindings.git>. (branch fixup)

I will submit this as a PR, except that if we do
$ swift build
$ swift test

it fails trying to get to the tests which needs to read in a datafile from the data directory.
I dimly recall Nick running into this before, and I forget what the solution was, but hopefully he remembers?

**Comment by ssteinbach** [comment]
Addressed in the swift repository.

**Comment by ssteinbach** [comment]
Closed by:  #871
