### ISSUE TITLE
Minor documentation fixes

### ISSUE THREAD

**Issue by darbyjohnston** [PixarAnimationStudios/OpenTimelineIO#913]
First of all, thanks for all of the nice documentation! I was just reading through it and noticed a couple of minor typos and small changes that could make the formatting more consistent. I'll create a PR for the suggested changes.

**Comment by meshula** [comment]
closed by https://github.com/PixarAnimationStudios/OpenTimelineIO/commit/93f5e362813cb0c3095adf6e28aa8409894de015
