### ISSUE TITLE
Add include directories to OpenTimeConfig.cmake/OpenTimelineIOConfig.cmake

### ISSUE THREAD

**Issue by darbyjohnston** [PixarAnimationStudios/OpenTimelineIO#915]
The auto-generated OpenTimeConfig.cmake/OpenTimelineIOConfig.cmake files are missing the include directories for the OTIO headers which makes compiling C++ programs difficult. This can be fixed by adding the "INCLUDES" argument to the install command for OpenTime/OpenTimelineIO. I'll submit a PR with the proposed change...

**Comment by meshula** [comment]
closed by https://github.com/PixarAnimationStudios/OpenTimelineIO/commit/600a9d758b7633ab341448caa410152eef6da3f8
