### ISSUE TITLE
Add C++ versions of each_child()/each_clip()

### ISSUE THREAD

**Issue by darbyjohnston** [PixarAnimationStudios/OpenTimelineIO#925]
It would be useful to have the each_child()/each_clip() functionality available in C++ for iterating over objects in a timeline. Currently these functions are Python only, located in timeline.py and composition.py.

**Comment by Viraj-Rana008** [comment]
I want to work on this.
Is each_child()/each_clip() need to be added here  
src/opentimelineio/composition.cpp , src/opentimelineio/timeline.cpp?

**Comment by darbyjohnston** [comment]
Hi, thanks for the offer of help! The changes for this are actually finished and were merged last week:
https://github.com/PixarAnimationStudios/OpenTimelineIO/pull/926

I guess I should close this issue to reflect that...
