### ISSUE TITLE
Non-ascii character in doc causing issues file_bundle_utils.py 

### ISSUE THREAD

**Issue by avrata** [PixarAnimationStudios/OpenTimelineIO#938]
### Incorrect Functionality and General Questions

I noticed a non-ascii char in "file_bundle_utils.py"

## To Reproduce

> otiopluginfo
...
SyntaxError: Non-ASCII character '\xc2' in file /scratch/opentimelineio-0.14dev1_pixar.02/lib/python2.7/site-packages/opentimelineio/adapters/file_bundle_utils.py on line 113, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by ssteinbach** [comment]
Closed by #939
