### ISSUE TITLE
Kid music

### ISSUE THREAD

**Issue by kid123jke** [PixarAnimationStudios/OpenTimelineIO#963]
## Feature Request

Is this a New Feature, or a Proposed Change to existing Behavior?

## Description

Describe the new feature, or describe the modification to existing behavior, and provide context as necessary to help with understanding how the feature relates to a workflow or functionality.

## Context

Add any other context here, such as simulated output, or screenshots, that might help clarify the request.

**Comment by meshula** [comment]
Thanks for your interest. Please consider opening an issue following the guidelines in the issue template, with a specific question about OpenTimelineIO. For more general help, you might consider looking at the documentation, linked from the main readme, or reviewing some of the other issues people have posted over the years.
